### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by toddrjen** [NeuralEnsemble/elephant#10]
Our minimum version requirements include numpy 1.5.0 and scipy 0.9.0.  However, our Ubuntu tests only test the latest version of all packages, and the miniconda tests only support numpy >= 1.6.2 and scipy >= 0.11.0.  

I am a bit uncomfortable listing dependencies that our tests cannot verify work properly.  Installing either numpy or scipy (not to mention both) manually in travis takes forever, so that is not a feasible approach. 

Even someone tests manually before official releases, a lot of small and subtle bugs sneak through that can be very hard to track to a specific change.  

So I am thinking it might be best to set our minimum dependencies versions to be the versions supported by travis or greater.  What does everyone else think?

**Comment by alperyeg** [comment]
@apdavison perhaps Numpy 1.9 is downloaded because in the requirements it is stated that the version should be higher than 1.6.2. So if Elephant is installed per pip e.g. in a virtualenv numpy 1.9 will be automatically downloaded and installed.

**Comment by apdavison** [comment]
@alperyeg That's not how I interpreted the message. He stated that he "needed" to install 1.9, which suggests to me that he already had an earlier version installed, and it didn't work. I guess I should follow up to find out which earlier version he tried and what the error message was.

**Comment by dizcza** [comment]
> set our minimum dependencies

We provide the versions as `scipy>=X.Y.Z` but this does not mean all X.Y.Z will work because it might clash with the requirement of another package. Therefore, the solution to this issue requires building a dependency tree, which, of course, is something we as the developers won't do.
