### ISSUE TITLE
lv() and cv2() raising an error for too short spike trains 

### ISSUE THREAD

**Issue by pietroquaglio** [NeuralEnsemble/elephant#115]
Currently the functions lv() and cv2() in statistics raise an error if the spike trains in input has less three spikes. It might be preferable to replace this with a warning message and returning NaN or None instead (suggested in #108 ). For example this avoids to break for loops over list of spike trains.

**Comment by mdenker** [comment]
I think this is a very general design decision to make: The safe solution is to error, the often more practical solution is to `nan`. Would it make sense to have functions such as the ones mentioned here error on default, but optionally only warn and return nan's?

**Comment by apdavison** [comment]
I agree with Michael's suggestion - have error as default, but add an optional argument to return NaN, so that the user has to be explicitly aware of the choice. (This means the error message needs to include information about the NaN option)

**Comment by alperyeg** [comment]
@EmanueleLucrezia can you fix this issue? Thanks!

**Comment by EmanueleLucrezia** [comment]
I can try to adapt the code from here: https://github.com/NeuralEnsemble/elephant/pull/171/files, where the same issue arose for empty spike trains and an argument 'with_nan' was introduced
