### ISSUE TITLE
Metadata for results

### ISSUE THREAD

**Issue by rproepp** [NeuralEnsemble/elephant#12]
I think this warrants its own issue:

@toddrjen wrote in #11:

> This also leads me to another issue I have been thinking about: what do we do about the metadata of a neo object? When, for example, we get the average spike rate of a spike train, we end up with just a quantity. Is that what we want? Might it be a good idea to have some class that stores the output of these sorts of analyses along with the metadata of the original neo object? Or is that overkill?
> 
> The problem with this is doing it in a generic manner. You can't really use a SpikeTrain, since the resulting object may not meet the rules of a SpikeTrain. On the other hand, creating a generic "results" class would make it impossible to know what metadata you should expect from an object. And having a more specific SpikeTrainResults object would be difficult since it would need to be able to handle scalars, 1D arrays, and maybe even ND arrays depending on what analyses we allow. So it is a difficult problem, but I think having some way to keep the metadata bound to the results of some manipulation is important.

I think this verges into overkill territory :-) For most results (like the average rate of a spike train), the caller knows exactly from what object the result has been calculated. The caller also knows if and what metadata is needed, while our analysis function doesn't, so I would leave the responsibility upstream.

However, there might be analysis where this information is not available to the caller. For example, an analysis that takes a number of objects, but only uses some of them based on their content. I don't know if we will have such functions - I would try to avoid it but it might be necessary for some algorithms. In that case, I would return providence information to the caller: provide which objects have actually been used. By linking results to the actual objects used in their creation, all metadata is available and we do not need to create new result types with all the complications that come with that.

**Comment by Moritz-Alexander-Kern** [comment]
For provenance tracking see Alpaca (Automated Lightweight Provenance Capture):

Documentation:
https://alpaca-prov.readthedocs.io/en/latest/

Code:
https://github.com/INM-6/alpaca

![](https://alpaca-prov.readthedocs.io/en/latest/_static/images/alpaca_logo.png)
