### ISSUE TITLE
Invalid window size/binwidth check

### ISSUE THREAD

**Issue by tristanstoeber** [NeuralEnsemble/elephant#122]
Hei,

In /spike_train_correlation.py,  function '_cch_speed' and '_cch_memory', I tried a binwidth of 0.4 and a windowsize of 40. The input validation raises the error "ValueError: The window has to be a multiple of the binsize" despite being obviously true. In my case 
win[0].rescale(binsize.units).magnitude % binsize.magnitude = 0.399999999998
So obviously a numerical issue with a simple tolerance solution

Best,
Tristan

**Comment by mdenker** [comment]
Hei Tristan,
thanks for you feedback.

I could replicate your problem on our machines using this code:
```python
binned_st1 = elephant.conversion.BinnedSpikeTrain(
    elephant.spike_train_generation.homogeneous_poisson_process(
    10. * pq.Hz, t_start=0 * pq.ms, t_stop=5000 * pq.ms),
    binsize=.4 * pq.ms)
binned_st2 = elephant.conversion.BinnedSpikeTrain(
    elephant.spike_train_generation.homogeneous_poisson_process(
    10. * pq.Hz, t_start=0 * pq.ms, t_stop=5000 * pq.ms),
    binsize=.4 * pq.ms)
cc_hist = elephant.spike_train_correlation.cross_correlation_histogram(
    binned_st1, binned_st2, 
    window=[-40*pq.ms,40*pq.ms],
    border_correction=False,
    binary=False, kernel=None, method='memory')
```

@alperyeg Can you also reproduce the error with this code? I am on
```python
In [35]: numpy.__version__
Out[35]: '1.13.3'
In [36]: pq.__version__
Out[36]: u'0.12.1'
```

**Comment by mdenker** [comment]
A current workaround is to specify the window using integer multiples of the binsize, i.e., in the above example:
```python
binned_st1 = elephant.conversion.BinnedSpikeTrain(
    elephant.spike_train_generation.homogeneous_poisson_process(
    10. * pq.Hz, t_start=0 * pq.ms, t_stop=5000 * pq.ms),
    binsize=.4 * pq.ms)
binned_st2 = elephant.conversion.BinnedSpikeTrain(
    elephant.spike_train_generation.homogeneous_poisson_process(
    10. * pq.Hz, t_start=0 * pq.ms, t_stop=5000 * pq.ms),
    binsize=.4 * pq.ms)
cc_hist = elephant.spike_train_correlation.cross_correlation_histogram(
    binned_st1, binned_st2, 
    window=[-10, 10],
    border_correction=False,
    binary=False, kernel=None, method='memory')
```

**Comment by alperyeg** [comment]
@mdenker I can reproduce the same error if I give a `quantity` as a parameter for the `window`. Otherwise
```python
(...) 
cc_hist = elephant.spike_train_correlation.cross_correlation_histogram(
    binned_st1, binned_st2, 
    window=[-40 ,40],
    border_correction=False,
    binary=False, kernel=None, method='memory')
```
does work for me, too. 
My setup is:
```python
In [8]: np.__version__
Out[8]: '1.13.1'
In [10]: pq.__version__
Out[10]: u'0.12.1'
``` 
We can make a small hot fix.

**Comment by dizcza** [comment]
It seems like we stick to passing integers (already rescaled to the binsize by a user) in `window` and this issue should have been closed.
I'll keep it open for a week for the feedback if any.
