### ISSUE TITLE
cch() got an unexpected argument 'cross_corr_coef'

### ISSUE THREAD

**Issue by FMendezSlc** [NeuralEnsemble/elephant#128]
Hi all.

First of all, I want to thank you for your work in this library. It has become my principal tool to work with spike trains, trying to keep it all in python.

Anyway, I noticed this error. Apparently, the normalization was never actually incorporated in the function as described in the documentation. Checked the source code of the package I've downloaded, version 0.4.1. It's simply not the same as the one shown in the documentation.

I suppose I can just copy the source code in the docs and fix mine but I guessed you'd like to know.

Thanks again.

**Comment by pietroquaglio** [comment]
Hi,
yes you are right, this was unfortunately due to the fact that we had a glitch when we built the documentation for version 0.4.1 and it is not aligned to that release, but it refers to a later version of the repo. 

In order to use the argument 'cross_corr_coef' you just need to checkout the master, instead of using version 0.4.1.

We will soon release a new version including the new functionalities, for which also the problem of the documentation should be solved!

Thanks a lot for letting us notice this and don't hesitate to contact us for any further problem!

**Comment by FMendezSlc** [comment]
Hi.
Thanks for the quick response. that's actually what I did once I realized
the code in the master branch was updated.
Following in this line, is there in the upcoming version a similar approach
for the implementation of the spike time tiling coefficient?

2018-01-31 8:15 GMT-06:00 Pietro Quaglio <notifications@github.com>:

**Comment by pietroquaglio** [comment]
I personally did not know such measure, but I just took a look to the original paper introducing it and it seems very interesting. As far as I know there it is not planned to implement it at the moment, so if by chance you have already a python implementation or you are willing to contribute of course you are very welcome. In any case I will now create a new issue suggesting the implementation of the spike tiling!

**Comment by FMendezSlc** [comment]
Hi again.

Sorry for the delay. I do have been working on a python implementation of
the original code by Cutts. I'm very pleased with it, now I'm working on
getting a parameter of the direction of the correlation.
Should I fork the project and put up a pull request or should someone
review it first?

Kind regards.

2018-02-02 3:29 GMT-06:00 Pietro Quaglio <notifications@github.com>:

**Comment by alperyeg** [comment]
@FMendezSlc please fork the project and start a pull request. Someone will review it then. 
Will this be an extension to the already existing method or something new?

**Comment by FMendezSlc** [comment]
As it is now, it's the python implementation of the method as published by
Cutts and Eglen following closely the C code (available at
https://github.com/CCutts/Detecting_pairwise_correlations_in_spike_trains/blob/master/spike_time_tiling_coefficient.c)
and making it fully compatible with the elephant library.

**Comment by alperyeg** [comment]
Merged with https://github.com/NeuralEnsemble/elephant/pull/136
