### ISSUE TITLE
travis: update to dist trusty 

### ISSUE THREAD

**Issue by alperyeg** [NeuralEnsemble/elephant#129]
Travis is discontinuing support for `Ubuntu precise` end of April 2018. Our travis script has explicitly `dist:precise` at the header. If not specified the Ubuntu build in the build matrix of travis produced errors before. So we should investigate this issue further on and change our travis script accordingly.
For more information see:  https://blog.travis-ci.com/2017-08-31-trusty-as-default-status

**Comment by alperyeg** [comment]
My runs with the only change `dist:precise` to `dist:truty` in the .yaml result in a timeout (arising from the cross-validation tests in the test csd module), which I cannot explain.

**Comment by dizcza** [comment]
Changed to `dist: xenial` in https://github.com/NeuralEnsemble/elephant/pull/222
