### ISSUE TITLE
Error in the function statistics.instantaneous_rate when kernel='auto'

### ISSUE THREAD

**Issue by pietroquaglio** [NeuralEnsemble/elephant#144]
The computation of the optimized kernel width return an error for spiketrain with few and very close spikes. Example to reproduce the error:
```python
import neo
import quantities as pq
import elephant.statistics as stat
st=neo.SpikeTrain([2.12,2.13,2.15]*pq.s, t_stop=10*pq.s)
rate = stat.instantaneous_rate(st,1*pq.ms)
```

**Comment by mdenker** [comment]
I can confirm this error in sskernel, and also that adding an additional spike a tiny bit further away works
`st=neo.SpikeTrain([2.12,2.13,2.15,2.16]*pq.s, t_stop=10*pq.s)`
