### ISSUE TITLE
Wrong rounding cause an error when window parameter is set for the cch

### ISSUE THREAD

**Issue by pietroquaglio** [NeuralEnsemble/elephant#146]
spike_train_correlation.cch() function raise an error also when the parameters window are a multiple of the binsize. Example:
```python
import elephant.spike_train_correlation as corr
import neo
import elephant.conversion as conv
import quantities as pq
sts1 = neo.SpikeTrain([1,2,3]*pq.s, t_stop=4*pq.s)
sts2 = neo.SpikeTrain([1,2,3]*pq.s, t_stop=4*pq.s)
window = [-0.1,0.1]*pq.s
binsize = 0.01*pq.s
cch = corr.cch(conv.BinnedSpikeTrain(sts1, 0.01*pq.ms),
             conv.BinnedSpikeTrain(sts2, 0.01*pq.ms),
             window=window)
```
This is due to the rounding error given by % operator (e.g. 0.1%0.01!=0). The control for such condition should be changed.

**Comment by alperyeg** [comment]
@pietroquaglio is this issue fixed?

**Comment by pietroquaglio** [comment]
Not yet, but I am preparing a pull request at the moment (coming latest end of this week)
