### ISSUE TITLE
Docstring example of SFC missing imports

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/elephant#148]
```
import quantities as pq
from quantities import s
```
is missing from the example in the SFC function

**Comment by mdenker** [comment]
#147 fixed the issue regarding the s. This leaves the issue on how to deal with the `pq`.
I am tempted to not specify `import numpy as np` and `import quantities as pq` in each example such as to not clutter code. However, maybe it's better to be completely consistent throughout and make no hidden assumptions about imports being available for examples to run.

**Comment by alperyeg** [comment]
IMO a doctest should be runnable. Each example shows how to use a function, in most cases people will copy the example and paste the code to try it out. That means the examples should be self-contained. This could imply to put imports everywhere in the example part of the docstrings. 
One could checkout the [doctest module](https://docs.python.org/3.5/library/doctest.html) if there are smarter solutions, but that probably leads to putting everywhere `import doctest`.

**Comment by mdenker** [comment]
Decision was made during the docathons that we agree with always putting all imports into the examples. Doc guidelines will be updated accordingly.
