### ISSUE TITLE
Integrate pep8 speaks?

### ISSUE THREAD

**Issue by alperyeg** [NeuralEnsemble/elephant#156]
Should we integrate pep8 speaks into Elephant? The tool checks for pep8 compatibility for ongoing pull requests. 

https://pep8speaks.com/
https://github.com/OrkoHunter/pep8speaks

**Comment by mdenker** [comment]
@apdavison I tried, but I cannot do this, since I am not owner of NeuralEnsemble. Could you please install the pep8 plugin when you get the chance? Thanks!

**Comment by apdavison** [comment]
Done.
