### ISSUE TITLE
Integration of optimized ASSET

### ISSUE THREAD

**Issue by alperyeg** [NeuralEnsemble/elephant#163]
Add the optimized ASSET module to Elephant. Atm the code lies in a private repository ([here](https://github.com/INM-6/pcp_use_cases/tree/clean_up)).
TODOs (more to add):

- [ ] Compare and merge `asset.py` with the code in the module
- [ ] Create an `asset` folder and put the necessary files in there. The module requires `cython` and other `c-based` files
- [ ] Adapt `setup.py` to compile the `c` files and include corresponding folder

**Comment by dizcza** [comment]
Integrated in the mentioned pull reques,t however, we stripped off Cython.
