### ISSUE TITLE
C[i, j] = C[j, i] = enumerator / denominator in corrcoef

### ISSUE THREAD

**Issue by neworderofjamie** [NeuralEnsemble/elephant#169]
I'm trying to plot cross-correlation histograms of the attached spike data using the following elephant code: 
```python
import numpy as np
from quantities import s, ms
from neo import SpikeTrain
from elephant.conversion import BinnedSpikeTrain
from elephant.spike_train_correlation import corrcoef

spikes = np.loadtxt("6E.txt", skiprows=1, delimiter=",",
                        dtype={"names": ("time", "id", ), "formats": (float, int)})

neuron_indices = np.random.choice(14395, 200, replace=False)
spike_times = [SpikeTrain(spikes["time"][spikes["id"] == n] * ms,t_stop=10*s)
                   for n in neuron_indices]

binned_spike_times = BinnedSpikeTrain(spike_times, binsize=2.0 * ms)
correlation = corrcoef(binned_spike_times)
```
The ``corrcoef`` function emits a warning of ``C[i, j] = C[j, i] = enumerator / denominator in corrcoef`` and I'm getting NaNs in the resultant correlation matrix. It is quite possible the problem is with my data, but other analysis looks totally fine  (raster plotting, CV ISI, rate histograms etc etc) and this warning is not helpful in determining the problem! I am using Elephant 0.5.0 from pip.
[6E.txt](https://github.com/NeuralEnsemble/elephant/files/2262287/6E.txt)

**Comment by neworderofjamie** [comment]
Some more investigation suggests that this is due to some of the spike trains containing no spikes but a more informative error would be extremely useful

**Comment by alperyeg** [comment]
Hi @neworderofjamie as you already have seen the error is in the `enumerator/denominator` step. The warning is a typical `numpy` warning. Either there is a division by zero so you get NaNs or some other strange mathematical operation. If you look at the results the values are close to zero and negative or NaN. 
@mdenker I think you wrote the function. Can you have a look if possible?

**Comment by alperyeg** [comment]
FYI: I also realized that the list `spike_times` contains some empty spike trains.

**Comment by alperyeg** [comment]
We made a fix for this issue. Addressed [here](https://github.com/NeuralEnsemble/elephant/pull/171)
