### ISSUE TITLE
Install neo from pip

### ISSUE THREAD

**Issue by alperyeg** [NeuralEnsemble/elephant#178]
At the moment `neo` is directly installed from the Gthub master branch. It should be installed via pip to have a stable working solution. 
Right now the problem is that the pip `neo 0.6.1` version is not compatible with the latest `numpy` version which we have in our scripts. 
I guess it is better to wait for the latest 0.7.0 release of `neo`.

**Comment by apdavison** [comment]
Can you give more details on the numpy version requirements?

**Comment by alperyeg** [comment]
In our installation script the oldest numpy version we use is 1.8.2. the latest one is 1.15.1. On my laptop I tried with numpy 1.10 which also failed. [Here](https://travis-ci.org/alperyeg/elephant/builds/435683814) is the travis output.

**Comment by alperyeg** [comment]
@apdavison shall I open an issue on the github page of neo?

**Comment by apdavison** [comment]
@alperyeg yes, that's a good idea

**Comment by alperyeg** [comment]
Can be closed, because it is a known problem. Best solution is to wait for `neo 0.7.`
