### ISSUE TITLE
test failed (unittest / nosetests)

### ISSUE THREAD

**Issue by lbazan** [NeuralEnsemble/elephant#188]
setup.py nosetests
Or
setup.py nosetests --with-coverage --cover-package=elephant --cover-erase
Or
setup.py -m unittest discover

+ /usr/bin/python2 setup.py nosetests --with-coverage --cover-package=elephant --cover-erase
running nosetests
running egg_info
writing requirements to elephant.egg-info/requires.txt
writing elephant.egg-info/PKG-INFO
writing top-level names to elephant.egg-info/top_level.txt
writing dependency_links to elephant.egg-info/dependency_links.txt
reading manifest file 'elephant.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'elephant/test/spike_extraction_test_data.npz'
no previously-included directories found matching 'doc/build'
writing manifest file 'elephant.egg-info/SOURCES.txt'
/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/asset.py:687: RuntimeWarning: invalid value encountered in divide
  AngCoeff = dY / dX
./home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/asset.py:687: RuntimeWarning: divide by zero encountered in divide
  AngCoeff = dY / dX
......................................................................./home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/cubic.py:220: RuntimeWarning: divide by zero encountered in double_scalars
  L * (L - 1) * (L - 2)))
/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/cubic.py:220: RuntimeWarning: divide by zero encountered in long_scalars
  L * (L - 1) * (L - 2)))
./home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/cubic.py:110: UserWarning: Test aborted, xihat= 11 > ximax= 10
  warnings.warn('Test aborted, xihat= %i > ximax= %i' % (xi, ximax))
...........................S.............................................................................../home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/pandas_bridge.py:63: FutureWarning: sortlevel is deprecated, use sort_index(level= ...)
  return obj.sortlevel(0, axis=axis, sort_remaining=True)
.........................................../home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_pandas_bridge.py:2760: RuntimeWarning: invalid value encountered in less
  targ[targ < targ_start] = np.nan
/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_pandas_bridge.py:2761: RuntimeWarning: invalid value encountered in greater
  targ[targ > targ_stop] = np.nan
../home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_pandas_bridge.py:2706: RuntimeWarning: invalid value encountered in less
  targ[targ < targ_start] = np.nan
./home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_pandas_bridge.py:2734: RuntimeWarning: invalid value encountered in greater
  targ[targ > targ_stop] = np.nan
...../usr/lib64/python2.7/site-packages/scipy/fftpack/basic.py:160: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  z[index] = x
/usr/lib64/python2.7/site-packages/scipy/signal/signaltools.py:1593: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  h = h[ind]
......../usr/lib64/python2.7/site-packages/scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]
....................../home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_signal_processing.py:126: RuntimeWarning: invalid value encountered in true_divide
  target = (signal.magnitude - m) / s
/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/signal_processing.py:128: RuntimeWarning: invalid value encountered in true_divide
  (sig.magnitude - m.magnitude) / s.magnitude,
./usr/lib/python2.7/site-packages/quantities/quantity.py:321: RuntimeWarning: divide by zero encountered in true_divide
  return np.true_divide(other, self)
..........................E.....EEEE../home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/spike_train_generation.py:335: RuntimeWarning: divide by zero encountered in true_divide
  mean_interval = 1 / rate.magnitude
......../home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/spike_train_generation.py:267: RuntimeWarning: invalid value encountered in sqrt
  number = np.ceil(n + 3 * np.sqrt(n))
............................/usr/lib64/python2.7/site-packages/scipy/signal/spectral.py:1382: RuntimeWarning: invalid value encountered in true_divide
  Cxy = np.abs(Pxy)**2 / Pxx / Pyy
............/usr/lib/python2.7/site-packages/neo/core/basesignal.py:119: RuntimeWarning: invalid value encountered in true_divide
  new_signal = f(other, *args)
/usr/lib/python2.7/site-packages/neo/core/basesignal.py:119: RuntimeWarning: invalid value encountered in divide
  new_signal = f(other, *args)
.E..E......................................................................................
======================================================================
ERROR: Test if the window parameter is correctly interpreted.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_spike_train_correlation.py", line 468, in test_window
    assert_array_equal(cch_win, cch_win_mem)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 865, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 750, in assert_array_compare
    hasval='+inf')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 714, in func_assert_same_pos
    x_id = func(x)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 749, in <lambda>
    func=lambda xy: xy == +inf,
  File "/usr/lib/python2.7/site-packages/neo/core/analogsignal.py", line 416, in __eq__
    if (self.t_start != other.t_start or
AttributeError: 'float' object has no attribute 't_start'

======================================================================
ERROR: test_peak_detection_threshold (elephant.test.test_spike_train_generation.AnalogSignalPeakDetectionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_spike_train_generation.py", line 80, in setUp
    with open(raw_data_file_loc, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/spike_extraction_test_data.txt'

======================================================================
ERROR: test_peak_detection_time_stamps (elephant.test.test_spike_train_generation.AnalogSignalPeakDetectionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_spike_train_generation.py", line 80, in setUp
    with open(raw_data_file_loc, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/spike_extraction_test_data.txt'

======================================================================
ERROR: test_spike_extraction_waveform (elephant.test.test_spike_train_generation.AnalogSignalSpikeExtractionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_spike_train_generation.py", line 109, in setUp
    with open(raw_data_file_loc, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/spike_extraction_test_data.txt'

======================================================================
ERROR: test_threshold_detection (elephant.test.test_spike_train_generation.AnalogSignalThresholdDetectionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_spike_train_generation.py", line 45, in test_threshold_detection
    with open(raw_data_file_loc, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/spike_extraction_test_data.txt'

======================================================================
ERROR: The output should be the same as the input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_sta.py", line 91, in test_only_one_spike
    assert_array_equal(STA, cutout)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 865, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 750, in assert_array_compare
    hasval='+inf')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 714, in func_assert_same_pos
    x_id = func(x)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 749, in <lambda>
    func=lambda xy: xy == +inf,
  File "/usr/lib/python2.7/site-packages/neo/core/analogsignal.py", line 416, in __eq__
    if (self.t_start != other.t_start or
AttributeError: 'float' object has no attribute 't_start'

======================================================================
ERROR: Signal should average to the input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.0/elephant/test/test_sta.py", line 64, in test_spike_triggered_average_with_n_spikes_on_constant_function
    assert_array_almost_equal(STA, cutout, 12)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 973, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 750, in assert_array_compare
    hasval='+inf')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 714, in func_assert_same_pos
    x_id = func(x)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/_private/utils.py", line 749, in <lambda>
    func=lambda xy: xy == +inf,
  File "/usr/lib/python2.7/site-packages/neo/core/analogsignal.py", line 416, in __eq__
    if (self.t_start != other.t_start or
AttributeError: 'float' object has no attribute 't_start'

Name                                                       Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------------------
elephant/__init__.py                                           8      2    75%   31-32
elephant/asset.py                                            418    260    38%   67-68, 92, 118-126, 204-250, 275-282, 313-321, 352-361, 371-380, 493-500, 507-511, 515-536, 566-596, 622, 766, 860-889, 959-1076, 1119-1165, 1207-1258, 1319-1328, 1378-1410, 1462, 1466, 1525, 1559, 1634, 1678, 1685
elephant/cell_assembly_detection.py                          372     82    78%   239, 255, 261, 288, 302-306, 320-322, 381, 405, 409-410, 418, 443-448, 454-455, 552-557, 673-682, 719-736, 747-764, 770-808, 981, 1003, 1095, 1098-1099
elephant/change_point_detection.py                           165     23    86%   107, 110, 179-180, 183-184, 187-188, 223-224, 227-228, 299, 301, 303, 305, 308, 310, 312, 314, 318, 473-474
elephant/conversion.py                                       182      3    98%   147, 803-804
elephant/cubic.py                                             56      0   100%
elephant/current_source_density.py                           160      6    96%   120-121, 130, 179-181, 198
elephant/current_source_density_src/KCSD.py                  331     56    83%   46, 49, 52, 66-68, 206-209, 277-278, 329-330, 923-924, 926-935, 944-953, 986-992, 1018-1019, 1022-1059
elephant/current_source_density_src/__init__.py                2      0   100%
elephant/current_source_density_src/basis_functions.py        42     16    62%   48-50, 81-83, 98-99, 131-132, 147-149, 164-166
elephant/current_source_density_src/icsd.py                  375     99    74%   94-100, 103-104, 108-109, 111-112, 114-115, 119-124, 139, 183-185, 197, 216, 283-286, 290-292, 300-303, 328, 392-395, 398-400, 408-411, 422, 446, 528-531, 534-536, 542-544, 569, 779-886
elephant/current_source_density_src/utility_functions.py     123     14    89%   30, 324-338
elephant/kernels.py                                          138      1    99%   171
elephant/neo_tools.py                                         49      0   100%
elephant/pandas_bridge.py                                     90      2    98%   98, 136
elephant/phase_analysis.py                                    48      0   100%
elephant/signal_processing.py                                114      1    99%   333
elephant/spade.py                                            394     89    77%   71, 296, 305-306, 319-320, 350, 360, 367, 370, 483-492, 647, 758, 780, 785-787, 931-932, 988-989, 1039, 1041, 1049, 1052, 1059, 1142, 1144, 1152, 1168-1179, 1187, 1192, 1204, 1217, 1222, 1328, 1461-1462, 1465, 1470-1496, 1513-1514, 1516-1517, 1520-1521, 1527-1554, 1623
elephant/spade_src/__init__.py                                 1      0   100%
elephant/spade_src/fast_fca.py                               749    575    23%   66-78, 82, 86, 96, 107-120, 124-137, 141-154, 158-172, 176, 197-198, 200-201, 225-229, 247, 316-352, 402-403, 412-439, 444-451, 456-458, 462-465, 468-471, 477-514, 520-541, 546-558, 563-575, 581-599, 605-628, 632-635, 638-661, 668-676, 687-698, 703-724, 728-755, 759-813, 823-858, 864-865, 868-879, 882-892, 905-922, 927-935, 941-965, 970-979, 984-1124
elephant/spectral.py                                         160     23    86%   107, 111, 119-122, 127-132, 136-139, 142, 144, 148-149, 153-161
elephant/spike_train_correlation.py                          185      1    99%   539
elephant/spike_train_dissimilarity.py                        126      2    98%   26-27
elephant/spike_train_generation.py                           303    107    65%   58-114, 147-171, 200-253, 291, 471, 515-516, 520, 525, 530-532, 536, 688, 754-755, 763, 794-803, 912-918
elephant/spike_train_surrogates.py                            70      2    97%   44-45
elephant/sta.py                                               92      5    95%   91, 253, 272-275
elephant/statistics.py                                       289     25    91%   48, 907, 916, 923, 1073, 1081, 1150-1160, 1168-1175, 1253, 1256, 1259
elephant/unitary_event_analysis.py                           193     22    89%   86, 143, 200, 278, 312, 387, 471, 477, 557, 565, 599-600, 638, 655, 742, 758, 763, 778, 792-796
----------------------------------------------------------------------------------------
TOTAL                                                       5235   1416    73%
----------------------------------------------------------------------
Ran 439 tests in 338.927s

FAILED (SKIP=1, errors=7)
error: Bad exit status from /var/tmp/rpm-tmp.BVaNjX (%check)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.BVaNjX (%check)

**Comment by mdenker** [comment]
Fixed by #203
