### ISSUE TITLE
Proper environment for documentation builds

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/elephant#206]
The previous environment for RTD documentation was too detailed in pinning versions numbers and thus breaking with the generic docker containers of RTD. Now, the environment file is very slim and contains few entries only. The goal of this issue is to ensure (i) a good specification of the build environment containing only necessary additional packages and their versions, and (ii) switching the doc build environment back to python 3 using the RTD config file.

**Comment by dizcza** [comment]
Done both (i) and (ii) in https://github.com/NeuralEnsemble/elephant/pull/230.

**Comment by dizcza** [comment]
I don't fully understand the problems but it seems the issue is outdated and should be closed. We have been using python 3 in RTD for quite a long time.
Right, wrong?
