### ISSUE TITLE
Rescaling Neo objects (mainly in time) before an analysis

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/elephant#208]
A topic that frequently comes up is how to treat the physical (`quantities`) units of a Neo object if one starts doing calculations with it. 

* One option to to select one unit (e.g., the time units of a spike train) and scale all other properties (e.g., `t_start`) and potentially other Neo objects to this selected physical unit. 
* An alternative is to simplify all units and convert them to SI, e.g., to `s` for time. 
* A third option could be to give users the option of specifying the default time units in which an analysis is conducted.

Many available codes go with the second option implicitly, by indicating that input data must be in a specific unit (often, ms). On the positive side, clear standard units makes the code easier to read. However, this approach also leads to a lot more unit conversions unless data are already in the precise SI unit. 

In terms of making recommendations when implementing functions in Elephant, are there any other pros or cons regarding either approach?

**Comment by apdavison** [comment]
I'm not sure I understand the issue. `quantities` should let you completely ignore this issue, as it takes care of scaling automatically; that's one of the reasons for using it in Neo.

**Comment by mdenker** [comment]
As additional background, this topic was raised in PR #199 with opposite and imho equally valid viewpoints by @pietroquaglio and @PaulinaDabrowska , and the point of this issue is to collect opinions on whether there are arguments for either way of dealing with this issue (and whether this is an issue at all).

@apdavison Yes, in principle this is true, that is indeed the beauty of quantities. However, in practice, when rescaling with quantities one may always encounter situations where the well-known floating point rounding problems occur, especially if your recording system has weird sampling units (for example, for Blackrock files you may have integer time indicies as time with a compound unit of `1/30000*s`, that will become approximate floats when converted to `s`.

Therefore, one could argue that the way that units are converted within an analysis function may make a tiny difference in the end result. To a certain degree, this is probably unavoidable due to the nature of machine precision, however, maybe by handling conversions in a consistent manner across functions one may be able to make analysis methods a little bit more comparable to one another.

For example, functions that always take `ms` as input basically ignore this problem and delegates it to the user. On the other hand, functions that always automatically and blindly convert to `ms` may make unnecessary conversions.

But I agree, the question is still fuzzy. I'll try to get some make up some example -- maybe that is the best way to approach this question.

**Comment by dizcza** [comment]
We should always rescale to the spiketrains or analog signals - data objects that are the most memory consuming in the arguments list. Otherwise, we run into the overhead of rescaling quantities, which is non-negligible.
