### ISSUE TITLE
SPADE: setup.py should download fim.pyd for windows

### ISSUE THREAD

**Issue by oraby** [NeuralEnsemble/elephant#212]
[`spade.py`](https://github.com/NeuralEnsemble/elephant/blob/009e80f4945e2c12249c6f43f9f6b76fb7d0f520/elephant/spade.py#L76-L83) fails to import `fim` module on windows as [`setup.py`](https://github.com/NeuralEnsemble/elephant/blob/009e80f4945e2c12249c6f43f9f6b76fb7d0f520/setup.py#L23-L36) downloads only the `.so` version of the library, while windows requires the `.pyd` variation. 

The windows precompiled `pyd` files are available in the same  [location](http://www.borgelt.net/pyfim.html) as the `.so`

**Comment by mdenker** [comment]
Thanks for the input, I'll have a look into this. I think the Windows version had not been considered so far.

**Comment by mdenker** [comment]
Fixed. but enhancement suggested in follow-up issue #214
