### ISSUE TITLE
Provide precompiled FIM modules via pip/conda packages

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/elephant#214]
Currently, the fim.so/fim.pyd precompiled files are supplied as a download from the author's website. A better option would be to have these libraries as classic dependencies, downloadable by pip/conda, as suggested by @jpgill86 in #213 .

**Comment by mdenker** [comment]
Quote from @jpgill86

> I discovered that conda-forge has builds of PyFim available here:
> 
> https://anaconda.org/conda-forge/pyfim/files
> 
> Among these are builds for Python 3.7, 3.6, and 2.7 on Windows. After running the code above with python=3.6 and getting a failure, I manually downloaded conda-forge's build for Python 3.6, replaced the fim.pyd downloaded by elephant with it, and voilà, it works.

**Comment by dizcza** [comment]
Indeed, pip and conda FIM package seems to be able to include `fim` lib properly. we can add fim package in requirements-extras

**Comment by dizcza** [comment]
https://pypi.org/project/fim/ does not work anymore. Amazing. A few days ago I checked and it worked. Since fim pypi release is not stable, we cannot rely on this. We can close the issue until we are pretty sure that fim pypi release is stable.

**Comment by mdenker** [comment]
SPADE is now provided with precompile C code as pip wheel.
