### ISSUE TITLE
BUILDSTDERR: urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by lbazan** [NeuralEnsemble/elephant#216]
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/usr/lib64/python3.7/urllib/request.py", line 1317, in do_open
BUILDSTDERR:     encode_chunked=req.has_header('Transfer-encoding'))
BUILDSTDERR:   File "/usr/lib64/python3.7/http/client.py", line 1229, in request
BUILDSTDERR:     self._send_request(method, url, body, headers, encode_chunked)
BUILDSTDERR:   File "/usr/lib64/python3.7/http/client.py", line 1275, in _send_request
BUILDSTDERR:     self.endheaders(body, encode_chunked=encode_chunked)
BUILDSTDERR:   File "/usr/lib64/python3.7/http/client.py", line 1224, in endheaders
BUILDSTDERR:     self._send_output(message_body, encode_chunked=encode_chunked)
BUILDSTDERR:   File "/usr/lib64/python3.7/http/client.py", line 1016, in _send_output
BUILDSTDERR:     self.send(msg)
BUILDSTDERR:   File "/usr/lib64/python3.7/http/client.py", line 956, in send
BUILDSTDERR:     self.connect()
BUILDSTDERR:   File "/usr/lib64/python3.7/http/client.py", line 928, in connect
BUILDSTDERR:     (self.host,self.port), self.timeout, self.source_address)
BUILDSTDERR:   File "/usr/lib64/python3.7/socket.py", line 707, in create_connection
BUILDSTDERR:     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
BUILDSTDERR:   File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo
BUILDSTDERR:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
BUILDSTDERR: socket.gaierror: [Errno -2] Name or service not known
BUILDSTDERR: During handling of the above exception, another exception occurred:
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "setup.py", line 26, in <module>
BUILDSTDERR:     'elephant/spade_src/fim.so')
BUILDSTDERR:   File "/usr/lib64/python3.7/urllib/request.py", line 247, in urlretrieve
BUILDSTDERR:     with contextlib.closing(urlopen(url, data)) as fp:
BUILDSTDERR:   File "/usr/lib64/python3.7/urllib/request.py", line 222, in urlopen
BUILDSTDERR:     return opener.open(url, data, timeout)
BUILDSTDERR:   File "/usr/lib64/python3.7/urllib/request.py", line 525, in open
BUILDSTDERR:     response = self._open(req, data)
BUILDSTDERR:   File "/usr/lib64/python3.7/urllib/request.py", line 543, in _open
BUILDSTDERR:     '_open', req)
BUILDSTDERR:   File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
BUILDSTDERR:     result = func(*args)
BUILDSTDERR:   File "/usr/lib64/python3.7/urllib/request.py", line 1345, in http_open
BUILDSTDERR:     return self.do_open(http.client.HTTPConnection, req)
BUILDSTDERR:   File "/usr/lib64/python3.7/urllib/request.py", line 1319, in do_open
BUILDSTDERR:     raise URLError(err)
BUILDSTDERR: urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by mdenker** [comment]
Hi @lbazan ,
thanks for sharing your error trace. Did you get this during installation using a system-wide installed python 3.7, e.g., using something like
`sudo pip install elephant`?

**Comment by mdenker** [comment]
Two more questions: 

Do you have a proxy server installed, i.e., does
`echo "$http_proxy"`
give back something other than a blank line?

And can you get your file manually using
`wget http://www.borgelt.net/bin64/py3/fim.so`

**Comment by mdenker** [comment]
There is a fix #217 that prevents setup.py from crashing if the corresponding download location is not available. I'd be interested if this solves your issue when you install from this fix:
`pip install git+https://github.com/INM-6/elephant.git@fix/urlerror`

**Comment by mdenker** [comment]
I am assuming this to be fixed by #217. Please re-open and provide additional info if the problem persists. Again, thanks for reporting.
