### ISSUE TITLE
Butterworth filtering and theta bandpass

### ISSUE THREAD

**Issue by jmbudd** [NeuralEnsemble/elephant#220]
Hi 

I have encountered what I think may be an issue with bandpass filtering for theta band using Elephant. For my working, see [1] and [2]; I have used a test signal with a sampling rate (fs) of 5000 Hz to match data I am analysing but which I can't share. 

I think this may arise because [signal_processing.py](https://github.com/NeuralEnsemble/elephant/blob/master/elephant/signal_processing.py) uses scipy 'ba' rather than 'sos' output for Butterworth filters and this problem arose for order > 3 (current default value is 4). 

Used scipy (1.2.1), elephant (0.6.2) and neo (0.7.1).

N.B. Originally posted on [NeuralEnsemble](https://groups.google.com/d/msg/neuralensemble/Q9Zs8p-8sJM/SIzCYDmnAQAJ)

[1]  [bandpass_test.pdf](https://github.com/NeuralEnsemble/elephant/files/3197578/bandpass_test.pdf)
[2] [bandpass_test.ipynb](https://github.com/jmbudd/misc/blob/master/bandpass_test.ipynb)

**Comment by mdenker** [comment]
Thanks for sharing your analysis and putting this report here from the mailing list. For a start, I definitely can reproduce the behavior you demonstrate.

**Comment by dizcza** [comment]
`scipy.butter` by default uses 'ba' output. I don't know why they stick to 'ba' rather than 'sos', I have little experience in frequency filtering. But I think, as it's done in all great python packages, it's due to the fact that, on average, it's working well, even though in some particular cases - one that you generously demonstrated - it might not work as expected. Since the first implementation of `signal_processing.butter`, 2015, to the best of my knowledge, you're the first one who encountered such an issue. So changing the default scipy's `ba` to `sos` just because of one particular case seems for me too much.

What we can do, however, is to add `output=ba` keyword in `signal_processing.butter` function. So you can change it to whatever you like. What do you think, is it worth doing so?

**Comment by jmbudd** [comment]
Thanks for your response. Yes, having the option to use 'sos' output would be helpful but the code would also need to include sosfiltfilt() filtering. But I am not sure I agree that 'ba' should remain the default because it seems best practice not to use this representation. This is not because there is a problem with scipy implement but that this method is numerically unstable (for discussion, see SO answer [1]): 

- Scipy [2] states " It’s recommended to use second-order sections format when filtering, to a void numerical error with transfer function (ba) format". See also scipy github [3] issue. 
- Matlab [4] states: "If you design the filter using the [b,a] syntax, you might encounter numerical problems. These problems are due to round-off errors and can occur for n as low as 4...." 

I may be the first person to have reported the issue but it is possible as their first use case of Elephant might have used this basic feature for analysing LFP signals, found it gave strange answers, and returned to scipy, matlab or igorpro. Had I not been part of HBP and expected to use this tool I might well have done this. 

[1] [ https://stackoverflow.com/questions/21862777/bandpass-butterworth-filter-frequencies-in-scipy | https://stackoverflow.com/questions/21862777/bandpass-butterworth-filter-frequencies-in-scipy ] 
[2] [ https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.butter.html#scipy.signal.butter | https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.butter.html#scipy.signal.butter ] 
[3] [ https://github.com/scipy/scipy/issues/2980 | https://github.com/scipy/scipy/issues/2980 ] 
[4] [ https://www.mathworks.com/help/signal/ref/butter.html | https://www.mathworks.com/help/signal/ref/butter.html ]

**Comment by dizcza** [comment]
Sorry for the late reply.
Can you please go through https://github.com/NeuralEnsemble/elephant/pull/234 or corresponding branch https://github.com/INM-6/elephant/tree/butter and check that it works as intended? I added one test for `sosfiltfilt` that compares its output with `filtfilt` and `lfilter`. Then I thought you might want to check it as well. Feel free to add comments into the PR.

**Comment by jmbudd** [comment]
@dizcza thanks for adding this new option. I ran the same tests in a new jupyter notebook to compare new 'sosfiltfilt' option with default 'filtfilt' option [1, 2]. For this single test case, the new option works well for both 4-th and 5-th order Butterworth bandpass filters.  

[1] [bandpass_test_sos.ipynb](https://github.com/jmbudd/misc/blob/master/bandpass_test_sos.ipynb)
[2] [bandpass_test_sos.pdf](https://github.com/jmbudd/misc/blob/master/bandpass_test_sos.pdf)
