### ISSUE TITLE
Wavelet transform bias

### ISSUE THREAD

**Issue by jmbudd** [NeuralEnsemble/elephant#223]
Hi

I have come across an apparent issue with the current implementation of the Morlet complex wavelet function used in [elephant.signal_processing.wavelet_transform()](https://github.com/NeuralEnsemble/elephant/blob/master/elephant/signal_processing.py). For my somewhat circuitous working, see [1] and [2]. 

According to the documentation, this implements the Morlet wavelet function described in Le Van Quyen et al. (2001) J Neurosci Meth 111:83-98. However, it appears the current code does not, as in Eqn 4 of Le Van Quyen et al., scale the function by the square root of the wavelet frequency. The result of this is that the wavelet power calculated from the output of the transform is increasingly underestimated at higher frequencies. A workaround for this issue seems to be to multiply the calculated wavelet power by its corresponding frequency. 

Used scipy (1.2.1), elephant (0.6.2) and neo (0.7.1).

[1] [cwt_power_test.pdf](https://github.com/NeuralEnsemble/elephant/files/3221007/cwt_power_test.pdf)
[2] [cwt_power_test.ipynb](https://github.com/jmbudd/misc/blob/master/cwt_power_test.ipynb)

**Comment by dizcza** [comment]
Thank you for pointing that out. We'll take a look and let you know.

**Comment by mdenker** [comment]
On request of the poster, temporarily closing the issue for now for some further cross-checking of the issue. Re-opening if necessary.
