### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by lbazan** [NeuralEnsemble/elephant#225]
======================================================================
ERROR: test_Riehle_et_al_97_UE (elephant.test.test_unitary_event_analysis.UETestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.2/elephant/test/test_unitary_event_analysis.py", line 464, in test_Riehle_et_al_97_UE
    local_test_dir + '/extracted_data.npy').item()
  File "/usr/lib64/python3.7/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/usr/lib64/python3.7/site-packages/numpy/lib/format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

======================================================================
ERROR: test_peak_detection_threshold (elephant.test.test_spike_train_generation.AnalogSignalPeakDetectionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.2/elephant/test/test_spike_train_generation.py", line 82, in setUp
    with open(raw_data_file_loc, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/elephant-0.6.2/elephant/test/spike_extraction_test_data.txt'

======================================================================
ERROR: test_peak_detection_time_stamps (elephant.test.test_spike_train_generation.AnalogSignalPeakDetectionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.2/elephant/test/test_spike_train_generation.py", line 82, in setUp
    with open(raw_data_file_loc, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/elephant-0.6.2/elephant/test/spike_extraction_test_data.txt'

======================================================================
ERROR: test_spike_extraction_waveform (elephant.test.test_spike_train_generation.AnalogSignalSpikeExtractionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.2/elephant/test/test_spike_train_generation.py", line 112, in setUp
    with open(raw_data_file_loc, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/elephant-0.6.2/elephant/test/spike_extraction_test_data.txt'

======================================================================
ERROR: test_peak_detection_threshold (elephant.test.test_spike_train_generation.AnalogSignalThresholdDetectionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.2/elephant/test/test_spike_train_generation.py", line 39, in setUp
    with open(raw_data_file_loc, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/elephant-0.6.2/elephant/test/spike_extraction_test_data.txt'

======================================================================
ERROR: test_threshold_detection (elephant.test.test_spike_train_generation.AnalogSignalThresholdDetectionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/elephant-0.6.2/elephant/test/test_spike_train_generation.py", line 39, in setUp
    with open(raw_data_file_loc, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/elephant-0.6.2/elephant/test/spike_extraction_test_data.txt'

----------------------------------------------------------------------
Ran 470 tests in 264.391s

FAILED (errors=6, skipped=1)
Test failed: <unittest.runner.TextTestResult run=470 errors=6 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=470 errors=6 failures=0>

**Comment by dizcza** [comment]
Please, provide the exact command of how you run the tests.
Also, specify your version of `neo` and `elephant` packages.

**Comment by sanjayankur31** [comment]
This is because the pypi tarball does not seem to include the data files required to run a few tests. Using the release tar from Github solves most of them. @dizcza : should the txt data files that are needed for the tests perhapse be included in the manifest so they end up in the pypi tarball?

**Comment by sanjayankur31** [comment]
```
$ tar -tvf elephant-0.6.2.tar.gz | grep "test_data.txt"
# returns nothing
```

**Comment by dizcza** [comment]
@sanjayankur31 a good catch. I'll add `spike_extraction_test_data` to package data. It's not a large file so we can afford including it.
@lbazan regarding your first error - it will be fixed in https://github.com/NeuralEnsemble/elephant/pull/222.
