### ISSUE TITLE
ERROR: test_cubic (elephant.test.test_cubic.CubicTestCase) on 32 bit arches

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/elephant#227]
We're building elephant for multiple arches for [neurofedora](https://docs.fedoraproject.org/en-US/neurofedora/overview/). This one test fails on 32 bit architectures only. Here's the output from a failed i686 build:

```
BUILDSTDERR: ERROR: test_cubic (elephant.test.test_cubic.CubicTestCase)
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILD/elephant-0.6.2/elephant/test/test_cubic.py", line 76, in test_cubic
BUILDSTDERR:     self.data_array, alpha=self.alpha)
BUILDSTDERR:   File "/builddir/build/BUILD/elephant-0.6.2/elephant/cubic.py", line 115, in cubic
BUILDSTDERR:     pval = _H03xi(kappa, xi, L)
BUILDSTDERR:   File "/builddir/build/BUILD/elephant-0.6.2/elephant/cubic.py", line 150, in _H03xi
BUILDSTDERR:     'kappa(2)= %f<%f=kappa(1)!!!' % (kappa[1], kappa[0]))
BUILDSTDERR: ValueError: H_0 can not be tested:kappa(2)= -0.130398<0.030000=kappa(1)!!!
BUILDSTDERR: ----------------------------------------------------------------------
```

- Failed i686 build: https://koji.fedoraproject.org/koji/taskinfo?taskID=35534431 
- The complete build log for this i686 build is here:  [elephant-i686-failed-build.txt](https://github.com/NeuralEnsemble/elephant/files/3289575/elephant-i686-failed-build.txt)
- This file includes what the "buildroot" was composed of---versions of packages and so on: [elephant-i686-failed-root.txt](https://github.com/NeuralEnsemble/elephant/files/3289581/elephant-i686-failed-root.txt)

Also fails on armv7hl:

- Failed armv7hl build: https://koji.fedoraproject.org/koji/taskinfo?taskID=35534721
- build log: [elephant-armv7hl-failed-build.txt](https://github.com/NeuralEnsemble/elephant/files/3289820/elephant-armv7hl-failed-build.txt)
- root log [elephant-armv7hl-failed-root.txt](https://github.com/NeuralEnsemble/elephant/files/3289821/elephant-armv7hl-failed-root.txt)

We're building against a git snapshot of neo, so maybe that's causing it. However, given that the test does not fail on 64 bit arches, it may not necessarily be the case. For completelness, here's an x86_64 build where the test did not fail:

- https://koji.fedoraproject.org/koji/taskinfo?taskID=35534537
- complete build log for this build: [elephant-x86_64-passed-build.log](https://github.com/NeuralEnsemble/elephant/files/3289617/elephant-x86_64-passed-build.log)
- complete root log: [elephant-x86_64-passed-root.log](https://github.com/NeuralEnsemble/elephant/files/3289618/elephant-x86_64-passed-root.log)

We've disabled this test temporarily. Could someone please have a look?
The spec file for the rpmbuild is here: https://src.fedoraproject.org/rpms/python-elephant/blob/master/f/python-elephant.spec

Please note that these failed builds will be removed from the build system in a few days, but I can always re-run them if more information is required.

**Comment by dizcza** [comment]
If you encounter other issues with 32-bit arch, please let us know.
