### ISSUE TITLE
[Bug] `import elephant` rendered useless by removal of imports in __init__.py

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/elephant#237]
@dizcza [said](https://github.com/NeuralEnsemble/elephant/pull/222#issuecomment-505037494)
> Now `fim.so` is downloaded at `pip install` and during the import (mostly to support travis tests).
> To do so, I merged version_file branch because it includes removing unnecessary imports at `elephant/__init__.py`

[This removal of all imports](https://github.com/NeuralEnsemble/elephant/commit/9458aa5758bfa42cb84afaed24e403c71d111928#diff-cf5c99a03a3651f3e9120185b8bfa91aL9) from `__init__.py` means that `import elephant` does nothing.

```python
In [1]: import elephant

In [2]: dir(elephant)
Out[2]:
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_get_version']
```

In order to use elephant, the user now has to manually import every subpackage they need by name. This breaks all code that uses `import elephant`! 👎👎

**Comment by dizcza** [comment]
Indeed, as you pointed out, `dir(elephant)` should contain useful internal packages. I'll revert the change back soon.

**Comment by jpgill86** [comment]
See also https://github.com/NeuralEnsemble/elephant/pull/231#discussion_r302662916.
