### ISSUE TITLE
[Feautre]  build with py 3.8

### ISSUE THREAD

**Issue by lbazan** [NeuralEnsemble/elephant#248]
Hi team ---

Does not work with py 3.8

Cheers,

**Comment by dizcza** [comment]
Python 3.8 is in pre-release mode and yet not officially supported in well-known packages like numpy. For example, there is en error for the latest python 3.8.0b4 trying to compile and install numpy 1.17.1. Once the python 3.8 becomes stable, we'll add support for it. For now, please use 3.7 (or 3.8 at your own risk).
