### ISSUE TITLE
Plans for compatibility with Neo 0.8.0?

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/elephant#253]
Neo 0.8.0 was released on September 30. Presently, elephant is marked as incompatible with it:

https://github.com/NeuralEnsemble/elephant/blob/c78af7ea6cff3645bab306393349aa7d89f05a13/requirements.txt#L1

Running ``pip install neo elephant`` in a new environment results in

```
ERROR: elephant 0.6.3 has requirement neo<0.8.0,>=0.7.1, but you'll have neo 0.8.0 which is incompatible.
Installing collected packages: numpy, quantities, neo, scipy, six, elephant
Successfully installed elephant-0.6.3 neo-0.8.0 numpy-1.17.2 quantities-0.12.3 scipy-1.3.1 six-1.12.0
```

Although pip printed an error, the installation completes, and the packages seem to work together.

However, continuous integration tests for projects that use Neo and elephant can be tripped up by this error. For example, my [neurotic](https://github.com/jpgill86/neurotic) project's tests are failing when previously they were passing because of this pip install error, and the only change was the release of Neo 0.8.0: [Travis CI build report](https://travis-ci.com/jpgill86/neurotic/jobs/228366279#L1467)

I could pin my project's requirements to the old version of Neo to get around this, but there are features in 0.8.0 I'd like to use, and this might not even be an option for other projects.

Are there plans for the near future to release a version of elephant with the Neo entry in ``requirements.txt`` bumped to allow version 0.8.0? Are there major obstacles to full compatibility with Neo 0.8.0 that I might be able to help with?

**Comment by dizcza** [comment]
Hi Jeffrey,

I'm currently looking at switching elephant to neo v0.8.0. There is one bug, however, reproduced several times in `test_neo_tools.py` that I don't understand - some breaking changes that, unfortunately, are not documented in neo v0.8.0 release notes. Now, `fake_neo('Block', seed=0)` returns a Block whose `array_annotations` field is an empty dict. Here is the traceback

```python
ERROR: test__extract_neo_attrs__epoch_noparents_array (elephant.test.test_neo_tools.ExtractNeoAttrsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ulianych/PycharmProjects/elephant/elephant/test/test_neo_tools.py", line 649, in test__extract_neo_attrs__epoch_noparents_array
    'durations': array_annotation_save['durations'],
KeyError: 'durations'
```

These failing tests are marked with a todo flag, so I'm not sure whether it's elephant issue or neo.

**Comment by apdavison** [comment]
Hi Danylo,

I'm not sure what that test is doing, but the "durations" and "labels" attributes of Epoch are no longer stored in array_annotations - see https://github.com/NeuralEnsemble/python-neo/pull/659

**Comment by dizcza** [comment]
Thank you, now it makes sense.
It should be in the master soon.

**Comment by jpgill86** [comment]
Excellent, thank you Danylo!
