### ISSUE TITLE
[Bug] BinnedSpikeTrain bin_edges do not match the actual binning

### ISSUE THREAD

**Issue by Kleinjohann** [NeuralEnsemble/elephant#255]
If t_stop - t_start is not divisible by binsize, the computed bin_edges do not match the actual binning. 

```
import quantities as pq
import numpy as np
import neo
import elephant

st = neo.SpikeTrain(times=np.array([2.5])*pq.s, t_start=0*pq.s, t_stop=3*pq.s)
bst = elephant.conversion.BinnedSpikeTrain(st, binsize=2*pq.s,
                                           t_start=0*pq.s, t_stop=3*pq.s)

print(bst.bin_edges)
print(bst.to_array())
```
returns
```
[0.  3. ] s
[[0]]
```

The bin_edges do not reflect the requested binsize, but the actual binning is correct (the spike did not end up inside the bin).

This is because we're using a linspace t_start,  t_stop and num_bins to compute the edges without taking the binsize into account: 
https://github.com/NeuralEnsemble/elephant/blob/c78af7ea6cff3645bab306393349aa7d89f05a13/elephant/conversion.py#L583-L601

**Comment by dizcza** [comment]
Thanks, Alex.

I'm struggling with what values `bin_edges` should take. Would you expect them to be `[0., 2., 3.]` in your case?

**Comment by Kleinjohann** [comment]
It should be `[0., 2.]`. It is crucial for many analyses that all bins have the same size, so if `t_stop - t_start` is not divisible by `binsize`, there will be some leftover time at the end. This is probably what was happening in #202 by the way, maybe we should document this better?

**Comment by dizcza** [comment]
Yes, I'll fix it and add this to docs because it wasn't obvious for me what you've just said. I also thought about the issue you mentioned (and the previous one in the list), but I guess this one is different. I'll check it anyway though.

**Comment by mdenker** [comment]
Discussed at meeting that this PR produces the desired behavior. One may consider throwing a warning to alert the user if the recording time is not divisible by the bin size.
