### ISSUE TITLE
[Bug] signal_processing.cross_correlation_function() scaling 

### ISSUE THREAD

**Issue by jmbudd** [NeuralEnsemble/elephant#265]
**Potential Issue**
The scaling of the cross correlation coefficient may not be correct at least for single pairs of AnalogSignals.

**Reproduce**
See notebook: https://github.com/jmbudd/misc/blob/master/ElephantCrossCorr.ipynb
(pdf of notebook: https://github.com/jmbudd/misc/blob/master/ElephantCrossCorr.pdf)

**Expected Behaviour**
The output from elephant code should match numpy/matlab version such that there is a stronger decay with time lag from peak correlation location. 

**Environment**
CPython 3.5.2
IPython 7.8.0
numpy 1.17.3
scipy 1.3.1
neo 0.7.2
elephant 0.6.3
compiler   : GCC 5.4.0 20160609
system     : Linux
release    : 4.4.0-165-generic
machine    : x86_64
processor  : x86_64
CPU cores  : 8
interpreter: 64bit

**Comment by dizcza** [comment]
Thank you for pointing this out! True, these functions should behave as numpy/scipy equivalent with the only difference that the input is AnalogSignal.
We're currently at Elephant workshop that will end on Wed, then I'll take a closer look.

**Comment by dizcza** [comment]
First of all, thank you for the reproducible notebook with the explanations. Seems your suggestion is right, though first I need to understand why the scaling was put in the first place. Maybe, the author of this function wanted to deal with the decaying tails on purpose, I'm not sure. And so I need to look up for the equation in the book the function references to.
I'll let you know once I get it through.

**Comment by jmbudd** [comment]
Thanks, Danylo. I think this is a right approach although I could not find the book cited.

**Comment by dizcza** [comment]
I cannot find the book either. But the comment at line 255

> Correct for bias due to zero-padding

explains the behavior. Maybe, it'd make sense to add a corresponding argument parameter `unbiased=True` like we do in [cross_correlation_histogram](https://github.com/NeuralEnsemble/elephant/blob/master/elephant/spike_train_correlation.py#L271) function.

The example you linked in the notebook does not mention bias correction at all. And I'm not sure what the behavior is expected by default in numpy/matlab equivalent - with or without bias correction?

**Comment by mdenker** [comment]
Link to Matlab scaling options: https://de.mathworks.com/help/matlab/ref/xcorr.html#d117e1608028

**Comment by jmbudd** [comment]
Thanks, Danylo and Michael, this explains the difference - abs(tau) term provides for an unbiased estimate, which numpy function does not. I agree adding a corresponding argument would make this clear and be more consistent with [cross_correlation_histogram](https://github.com/NeuralEnsemble/elephant/blob/master/elephant/spike_train_correlation.py#L271).

**Comment by dizcza** [comment]
Hello @jmbudd 
I added the flag `scaleopt` in the function. If you pass `scaleopt='coeff'`, it works the same as your numpy example. Feel free to check.
