### ISSUE TITLE
[Feature] Add `to_spiketrain_list()` to `BinnedSpiketrain` object

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/elephant#310]
**Feature**
Currently, the conversion module can convert `Spiketrain` to a matrix, but the reverse conversion is not possible. Needed would be a member function `to_spiketrain_list()`.

**Motivation**
See #309

**Comment by dizcza** [comment]
We have `lst_input` property of a BinnedSpikeTrain that stores the input spike train, so `to_spiketrain_list()` function should be just `.spiketrains` property.
I agree with renaming `lst_input` -> `spiketrains`. I never noticed how the input spiketrains are stored. Whatever reasons there were to call it like this, the name is surely misleading.
I'll fix it gracefully.

**Comment by dizcza** [comment]
I see what you mean now. The input can be already a binned matrix. Then `.spiketrains` property is not a list of SpikeTrains. OK, let's discuss this during one of our meetings.
