### ISSUE TITLE
[Deprecation warning] Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated.

### ISSUE THREAD

**Issue by morales-gregorio** [NeuralEnsemble/elephant#314]
Hey! I encountered the following warning:
```
[...]/elephant/spike_train_correlation.py:682: FutureWarning:Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated.
In future, it will be treated as `np.int64 == np.dtype(int).type`.
```

Which is raised in the `cross_correlation_histogram` function at:

https://github.com/NeuralEnsemble/elephant/blob/d6e98f9f6132bbd834853916fefd6385841053a2/elephant/spike_train_correlation.py#L681-L682

Changing `int` -> `np.int64` fixes it.  `int` -> `np.int32` would also work.

But maybe there is something else to this I am not considering.

Cheers,
Aitor

**Comment by dizcza** [comment]
Thank you, Aitor.
I was lazy to fix it, but since you mention it, I'll come up with a fix.
Basically, I need to resolve the following mutually exclusive problems:
```
np.issubdtype(np.int32, np.int64)
False
np.issubdtype(int, np.int32)
False
```
That's why I put int there, but sadly, it throws a warning.

**Comment by dizcza** [comment]
Reopen if it didn't work for you

**Comment by morales-gregorio** [comment]
Hey Danilo, Super quick! Thanks! It is gone :)
