### ISSUE TITLE
[Feature] Make CSD coordinates quantities

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/elephant#334]
**Feature**
Allow `ele_xx`, `ele_yy`, `ele_zz`, `x_lims`, `y_lims` and `z_lims` as function arguments of [`generate_lfp`](https://github.com/NeuralEnsemble/elephant/blob/c3fd35d478b2b05216ccb3a4e56fd67f9d1e48c6/elephant/current_source_density.py#L204) to be quantity objects.

**Motivation**
These arguments describe physical properties and should therefore for completeness also be handled with units as it is standard within Neo and Elephant.

**Alternatives**
Leave it as it is.

**Comment by dizcza** [comment]
We didn't discuss this issue yet but I think your point should be a part of a larger issue of the complete refactoring of the function. That's being done, we can allow the abovementioned parameters to be quantities.

**Comment by Moritz-Alexander-Kern** [comment]
Out of scope, feel free to reopen this at any time.
