### ISSUE TITLE
Calculating Variance Explained in GPFA analysis.

### ISSUE THREAD

**Issue by neurorishika** [NeuralEnsemble/elephant#337]
**Question**

Hey, how do I calculate the variance explained by the latent dimensions of GPFA analysis on spike trains? We need the variance explained by each of the latent dimensions.

_Please note that this issue tracker is not a help form and this issue may be closed and redirected to a more appropriate communication channel. Before asking a new question, please check our [NeuralEnsembe forum](https://groups.google.com/forum/#!forum/neuralensemble), where you can discuss any NeuralEnsemble resource, including Elephant._

**Comment by dizcza** [comment]
Hello Rishika,
I'm not sure if GPFA offers this: GPFA != PCA. GPFA operates with log-likelihoods, not variance.
@Junji110 could you please elaborate? Maybe I'm wrong after all.

P.S. As for the future questions, please ask them on the [NeuralEnsembe forum](https://groups.google.com/forum/#!forum/neuralensemble). We answer the questions there as frequently as they were asked on github.

**Comment by Junji110** [comment]
Danylo is correct.
In the GFPA framework there is no measure which is directly comparable to the explained variance in the PCA framework.
You could infer variances in which directions (in the neuron space) are represented more (or less) in the latent variables by examining `Corth` and the variances of the latent variables themselves, but they cannot be interpreted as the explained variance of the original data.
