### ISSUE TITLE
Citation for elephant

### ISSUE THREAD

**Issue by sje30** [NeuralEnsemble/elephant#344]
Hi,

We have been using the elephant package, and would like to cite it in a paper we are writing.  What is the best citation you'd like us to use for citing your package?  Is there an appropriate paper?

Thanks,
Stephen

cc: @as2875

**Comment by mdenker** [comment]
Dear Stephen, thanks for bringing this up - we'll include a citation page in the next release (#345). 

Currently, the best way to refer to Elephant is via its RRID:

> Elephant (RRID:SCR_003833)

which points to the [Elephant record on Scicrunch](https://scicrunch.org/resolver/scr_003833).


While a proper manuscript is currently underway, for now the best way to cite Elephant generically is
* **Denker M, Yegenoglu A, Grün S (2018) Collaborative HPC-enabled workflows on the HBP Collaboratory using the Elephant framework. Neuroinformatics 2018, P19. doi: 10.12751/incf.ni2018.0019**
```bibtex
@conference{elephant18,
    author = {Denker, M. and Yegenoglu, A. and Grün, S.},
    title = {{C}ollaborative {HPC}-enabled workflows on the {HBP} {C}ollaboratory using the {E}lephant framework},
    year = {2018}
    booktitle = {Neuroinformatics 2018},
    pages = {P19},
    doi = {10.12751/incf.ni2018.0019},
    url = {https://abstracts.g-node.org/conference/NI2018/abstracts#/uuid/023bec4e-0c35-4563-81ce-2c6fac282abd},
    }
```

Journal articles directly coupled to concrete implementations in Elephant are:
* **V. Rostami,  J. Ito, M. Denker, and S. Grün. [Re] Spike synchronization and rate  modulation differentially involved in motor cortical function. ReScience, 3(1):3, 2017. doi: 10.5281/zenodo.583814.**
* **A. Stella, P. Quaglio, E. Torre, and S. Grün. 3d-SPADE: Significance evaluation of spatio-temporal patterns of various temporal extents. Biosystems, 185:104022, 2019. doi: 10.1016/j.biosystems.2019.104022.**
```bibtex
@article{Stella19_104022,
  title = {3d-{SPADE}: {S}ignificance evaluation of spatio-temporal patterns of various temporal extents},
  author = {Stella, A. and Quaglio, P. and Torre, E. and Gr{\"u}n, S.},
  year = {2019},
  journal = {Biosystems},
  volume = {185},
  pages = {104022},
  doi = {10.1016/j.biosystems.2019.104022}
}

@article{Rostami17_3,
  title = {[{Re}] {S}pike synchronization and rate modulation differentially involved in motor cortical function},
  author = {Rostami, V. and Ito, J. and Denker, M. and Gr{\"u}n, S.},
  year = {2017},
  journal = {ReScience},
  volume = {3},
  number = {1},
  pages = {3},
  doi = {10.5281/zenodo.583814}
}
```

**Comment by sje30** [comment]
super, thank you.  I will use the 2018 paper for now.

Stephen
