### ISSUE TITLE
[Bug] Asset tutorial doesn't run locally

### ISSUE THREAD

**Issue by pbouss** [NeuralEnsemble/elephant#348]
The !wget command in the third cell of the ASSET tutorial does not work in an Apple OS. Thus, the dataset is not downloaded.

Maybe this can be changed against an OS-specific command. For iOS, this would be "curl".

**Comment by dizcza** [comment]
very valid point
yes, please open a pull request followed by substituting wget by curl

**Comment by dizcza** [comment]
Fixed in #350.
