### ISSUE TITLE
sskernel() routine for optimal kernel bandwidth BUGGY

### ISSUE THREAD

**Issue by etorre** [NeuralEnsemble/elephant#35]
The routine sskernel() works (implicitly! bad) only for gaussian kernel. Besides, when generating kernels it wrongly sets the kernel sigma (which for gaussian is ~bandwidth/5.5) to the kernel bandwidth and therefore effectively generates kernels which are 5.4 times larger than they should

**Comment by alperyeg** [comment]
Yes it only works for Gaussian kernels, that should be stated in the documentation.
@rmeyes can you look into this issue?

**Comment by rmeyes** [comment]
The bug is fixed and a pull request is issued.
