### ISSUE TITLE
[Feature] Fast instantaneous_rate for many spike trains 

### ISSUE THREAD

**Issue by gyyang** [NeuralEnsemble/elephant#361]
**Feature**
Improve instantaneous_rate to be faster when processing many spike trains

**Motivation**
It is often necessary to compute the rate of many neurons or many trials, using the same ```t_start, t_stop, sampling_period```. The current code appears rather slow for this purpose. There are many places that can be sped-up by parallelization and by not using Neo format. The following is some code that speeds things up by **~50-60X** for reasonable data size, i.e. ~1000 units, 10,000 spike each. The code is not extensively tested for edge cases, but does have the same output as the original code when ```kernel.sigma``` and ```t_stop - t_start``` are both integer multiples of ```sampling_period```.

**Alternatives**
```
import warnings
import numpy as np
import scipy

from elephant.statistics import optimal_kernel_bandwidth
import elephant.kernels as kernels


def myrate(spiketrain, sampling_period, kernel='auto',
                       cutoff=5.0, t_start=None, t_stop=None, trim=False,
                       center_kernel=True):
    """
    Estimates instantaneous firing rate by kernel convolution.

    Modified by gryang from elephant.statistics.instantaneous_rate. Much
    faster for many spike trains.

    Parameters
    ----------
    spiketrain : list of lists of spike times in seconds
    sampling_period : float
        Time stamp resolution in seconds of the spike times. The same resolution will
        be assumed for the kernel.

    The rest are the same as elephant.statistics.instantaneous_rate,
    abbreviated here.
    """

    if kernel == 'auto':
        kernel_width_sigma = None
        if len(spiketrain) > 0:
            kernel_width_sigma = optimal_kernel_bandwidth(
                spiketrain.magnitude, times=None, bootstrap=False)['optw']
        if kernel_width_sigma is None:
            raise ValueError(
                "Unable to calculate optimal kernel width for "
                "instantaneous rate from input data.")
        kernel = kernels.GaussianKernel(kernel_width_sigma * spiketrain.units)
    elif not isinstance(kernel, kernels.Kernel):
        raise TypeError(
            "'kernel' must be either instance of class elephant.kernels.Kernel"
            " or the string 'auto'. Found: %s, value %s" % (type(kernel),
                                                            str(kernel)))

    # TODO: do the single spike train case
    n_spiketrain = len(spiketrain)  # Number of spike trains

    # main function:
    nbins = int((t_stop - t_start) / sampling_period) + 1
    time_vectors = np.zeros((n_spiketrain, nbins))
    ranges = (t_start, t_stop+sampling_period)
    for i, st in enumerate(spiketrain):
        # See https://iscinumpy.gitlab.io/post/histogram-speeds-in-python/
        # time_vectors[i], _ = np.histogram(st, bins=nbins, range=ranges)
        c = ((st[(st >= ranges[0]) & (st < ranges[1])] - ranges[0]) /
             sampling_period).astype(np.int_)
        time_vectors[i] = np.bincount(c)

    # This line is necessary to match elephant's original implementation
    time_vectors[:, -1] = 0
    time_vectors = time_vectors.T  # make it (time, units)
    time_vectors = time_vectors.astype(np.float64)  # from elephant

    if cutoff < kernel.min_cutoff:
        cutoff = kernel.min_cutoff
        warnings.warn("The width of the kernel was adjusted to a minimally "
                      "allowed width.")

    sigma = kernel.sigma.rescale(pq.s).magnitude
    t_arr = np.arange(-cutoff * sigma, cutoff * sigma + sampling_period,
                      sampling_period) * pq.s

    if center_kernel:
        # keep the full convolve range and do the trimming afterwards;
        # trimming is performed according to the kernel median index
        fft_mode = 'full'
    elif trim:
        # no median index trimming is involved
        fft_mode = 'valid'
    else:
        # no median index trimming is involved
        fft_mode = 'same'

    _kernel = kernel(t_arr).rescale(pq.Hz).magnitude[:, np.newaxis]
    rates = scipy.signal.fftconvolve(
        time_vectors, _kernel, mode=fft_mode, axes=0)

    median_id = kernel.median_index(t_arr)
    # the size of kernel() output matches the input size
    kernel_array_size = len(t_arr)
    if center_kernel:
        # account for the kernel asymmetry
        if not trim:
            rates = rates[median_id: -kernel_array_size + median_id]
        else:
            rates = rates[2 * median_id: -2 * (kernel_array_size - median_id)]
    else:
        # (to be consistent with center_kernel=True)
        # n points have n-1 intervals;
        # instantaneous rate is a list of intervals;
        # hence, the last element is excluded
        rates = rates[:-1]

    return rates


if __name__ == '__main__':
    import time
    import quantities as pq
    from elephant.statistics import instantaneous_rate
    from neo.core import SpikeTrain
    from elephant.kernels import GaussianKernel
    import neo

    sampling_period = 0.01
    t_start = -2
    t_stop = 2
    X = [np.random.uniform(-3, 3, size=(np.random.randint(9000, 11000),)) for i
         in range(100)]
    kernel_sigma = 0.05
    kernel = GaussianKernel(50 * pq.ms)

    t0 = time.time()
    Rate = list()
    for i in range(len(X)):
        spiketrain = SpikeTrain(X[i] * pq.s, t_start=-3*pq.s, t_stop=3*pq.s)
        rate = instantaneous_rate(spiketrain, sampling_period=0.01 * pq.s,
                                  t_start=-2 * pq.s, t_stop=2 * pq.s,
                                  kernel=kernel)
        Rate.append(rate.magnitude[:, 0])
    Rate = np.array(Rate).T
    time_taken0 = (time.time() - t0)

    t0 = time.time()
    Rate2 = myrate(X, sampling_period=0.01, t_start=-2, t_stop=2,
                   kernel=kernel)
    time_taken1 = (time.time() - t0)
    print('Original {:0.4f}s, New {:0.4f}s, Speed up {:0.2f}X'.format(
        time_taken0, time_taken1, time_taken0/time_taken1
    ))

    print('Results are the same:', np.allclose(Rate, Rate2))


```

**Comment by dizcza** [comment]
Is `rates` a 2d array or concatenated 1d? At first glance, it looks like 2d.
We do support a list of spike trains but the behavior is to concatenate and sort the input spike trains prior to computing the instantaneous rate. I was wondering why we don't support 2d array input - 2d array output.
Since the current behavior is to concat the arrays, we need to discuss how to implement both features - with the concatenation and without (your case). An additional parameter such as `concatenate=True` could take place.
Your solution proves that the current code can be easily extended to the 2d case.

We're currently occupied with the 2nd Elephant Workshop preparation (check it out [here](https://www.humanbrainproject.eu/en/education/participatecollaborate/infrastructure-events-trainings/2nd-elephant-user-workshop/) if you haven't yet registered - the registration link still should work for an extra week); even if I implement this feature and fix the previous issue, it could take time before the pull request(s) are merged into the master branch.

On the other hand, we could already try-out this parallelization feature at the workshop... let's see.

**Comment by dizcza** [comment]
You've almost provided a solution. We've not discussed it yet but adding a default parameter `concatenate=True` and refactoring the logic a bit such that it supports both a single spiketrain and a list of spiketrains is a way to go, as for me.
Would you be willing to create a pull request for this? Let me know. Otherwise, I'll do it.

P.S. The previous issue is fixed in https://github.com/NeuralEnsemble/elephant/pull/362

**Comment by gyyang** [comment]
```rates``` is a 2D array (times, units).

On my side, I don't need this feature implemented anytime soon, so please feel free to implement it whenever you see fit. 

If I may take this opportunity to add some more suggestions, I suggest this code could support both neo.core.SpikeTrain and numpy arrays as inputs.

Thank you for fixing the previous issue and for the information about the workshop!

**Comment by dizcza** [comment]
Done.

The speedup we gained is x25..30, and the extra x2 comes from the fact you're not using quantities. I'll consider support for numpy arrays for "advanced" users that can deal with units on their own.

Thank you for the link to np.histogram benchmarks - we use this function in several places in Elephant, and it makes sense to optimize all of them at once. I'll look into this separately.
