### ISSUE TITLE
[Feature]  'confidence interval' or 'standard deviation' to output from statistics.instantaneous_rate

### ISSUE THREAD

**Issue by TRuikes** [NeuralEnsemble/elephant#363]
**Feature**
Add a 'confidence interval' or 'standard deviation' to output from [`statistics.instantaneous_rate`](https://github.com/NeuralEnsemble/elephant/blob/daa6f2d998b76c173aa48a61b951396e63dea86c/elephant/statistics.py#L552).

**Motivation**
When visualizing firing rates, or comparing firing rates between conditions, we often plot the mean firing rate and annotate the standard deviation with a shaded area to inform the reader how variable the signal is across trials ([random example](https://pubmed.ncbi.nlm.nih.gov/28548084/#&gid=article-figures&pid=figure-2-uid-1)). It might be usefull to have an attribute `rates.std`.

**Alternatives**
any name or method for estimating/visualizing variance will do

**Comment by dizcza** [comment]
Hello Thijs,

if I understand correctly, the scenario you have in mind is when you pass a list of spiketrains to the instantaneous rate function and expect to have an averaged instantaneous rate profile with some sort of deviation measure that describes how the rate profile differs from trial to trial.
Currently, the default behavior of the `instantaneous_rate` function when the input is a list of spiketrains is to concatenate them into a merged spiketrain, hence increasing the total rate. While I'm wondering what is the purpose of such a concatenation and sorting the spikes, and why we're having this in Elephant, I'm currently implementing a scenario, asked in #361, with an additional flag `concatenate=False` in which the output will be a 2d rate matrix of shape `(time, n_trials)`, thus preserving the information about the trials. Then you can easily get a standard deviation (the rate profiles will be aligned in time) as you typically do with a numpy array: `std = rates.std(axis=1)` - a vector of length `time` of the standard deviations across the trials. Then you can plot the mean rate, computed as `rate_mean = rates.mean(axis=1)`, and the std.

Is that what you mean?

**Comment by TRuikes** [comment]
ooops, my fault, I thought I'd use this to average (hadn't read  the docstring properly), it makes more sense to then indeed estimate the firing rate per trial and I'll get the average+std over those (hadn't thought of that :s). 
Your solution would indeed do the same thing, but I can see how that would make using the method more confusing.

**Comment by dizcza** [comment]
I agree, the current behavior with a list of spiketrains is nonintuitive (averaging seems more intuitive for me as well) and I'm voting for removing it completely - then we don't need to introduce yet another confusing flag as `concatenate=False` at the cost of breaking the functionality...
But it's better to break the compatibility than have a misused API.

**Comment by dizcza** [comment]
Now the output is a 2d matrix in case of multiple input spike trains.
So you can use `.mean()` and `.std()` methods directly.
