### ISSUE TITLE
Plans to keep requirements.txt forwards-compatible with future versions of Neo?

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/elephant#369]
I was wondering if #366 indicates a policy change to how Elephant's dependency on Neo will be expressed in `requirements.txt` going forward.

Last year, in #253, I described how pinning the version of Neo to a particular major release (e.g., `neo>=0.7.1,<0.8.0` or `neo>=0.8.0,<0.9.0`) puts limitations on how other packages and projects use Neo and Elephant together. Of course, if it is known that the next major release of Neo will be incompatible with Elephant, this policy makes sense. But I was wondering if the pinning used in the past (possibly because Neo was undergoing major changes?) is less likely to occur in the future, or if I should expect Elephant to soon require `neo<0.10.0`.

Thanks to anyone who can shed some light on this for me!

**Comment by dizcza** [comment]
Neo is currently underlying [a large change](https://github.com/NeuralEnsemble/python-neo/pull/817). Though Elephant tests are not affected, some notebooks might fail.
The last pull request that you mentioned is a hotfix for the 2nd Elephant User Workshop that will happen soon. After the workshop, we'll probably continue bounding from above though I don't like it very much either. We do need to be sure that all previous pip installable Elephant packages pick correct Neo versions, especially if we want to fix the version of elephant in papers.

An alternative would be to manually change `neo<0.10.0` for each Elephant release, but it includes the probability of forgetting it...

**Comment by jpgill86** [comment]
I see. I had not been tracking those major changes coming to Neo. It makes sense to guard against future compatibility issues if they seem likely to affect Elephant.

> We do need to be sure that all previous pip installable Elephant packages pick correct Neo versions, especially if we want to fix the version of elephant in papers.

Reproducibility is certainly very important. It seems that the pinning is intended to guarantee reproducibility for users who only cite the version of Elephant they used, without also explicitly citing their version of Neo. This strikes me as a bad habit to encourage, since the only way to guarantee reproducibility is by accounting for the entire Python environment (e.g., with `pip freeze`, published as a `requirements.txt` with the study's codebase), but I appreciate the convenience this provides for users who need to use an old version of Elephant for some reason.

Thanks for clarifying @dizcza!
