### ISSUE TITLE
[Bug] out-of-bounds error for spike_triggered_phase of sliced signals

### ISSUE THREAD

**Issue by rgutzen** [NeuralEnsemble/elephant#381]
**Describe the bug**
When slicing an analogsignal there might be a gap between the last sample point and `t_stop` from as much as 1/sampling_rate.
In the `spike_triggered_phase()` function, spike times are related to the nearest sample point in the analogsignal. When a spike, however, falls into the gap between the last sample point and `t_stop` it might be rounded so that the function tries to get an item that is just outside of the analogsignal slice.

**To Reproduce**
```
asig = neo.AnalogSignal(np.arange(20)*pq.dimensionless,
                        sampling_rate=1*pq.Hz,
                        t_start=0*pq.s)
hilbert = elephant.signal_processing.hilbert(asig)

st = neo.SpikeTrain(np.array([1,4,5,8,9.5,12,17])*pq.s, 
                    t_stop=20*pq.s)

hilbert_slice = hilbert.time_slice(0*pq.s, 10*pq.s)
st_slice = st.time_slice(0*pq.s, 10*pq.s)

phases, magnitude, time = elephant.phase_analysis.spike_triggered_phase(
                hilbert_slice, st_slice, interpolate=False)
```

```
~/anaconda3/envs/ewsk/lib/python3.7/site-packages/elephant/phase_analysis.py in spike_triggered_phase(hilbert_transform, spiketrains, interpolate)
    141             # positive if spike time is later than sample point
    142             print(spike_i, ind_at_spike_j)
--> 143             dv = spiketrain[sttimeind[spike_i]] - times[ind_at_spike_j]
    144 
    145             # Make sure ind_at_spike is to the left of the spike time

~/anaconda3/envs/ewsk/lib/python3.7/site-packages/quantities/quantity.py in __getitem__(self, key)
    372     @with_doc(np.ndarray.__getitem__)
    373     def __getitem__(self, key):
--> 374         ret = super(Quantity, self).__getitem__(key)
    375         if isinstance(ret, Quantity):
    376             return ret

IndexError: index 10 is out of bounds for axis 0 with size 10
```

A quick fix would be to simply check for this specific case with an if-statement and if necessary reduce the index by 1.
Or is there a more elegant solution?

**Comment by dizcza** [comment]
> A quick fix would be to simply check for this specific case with an if-statement and if necessary reduce the index by 1.

Such a fix indicates the wrong logic in the first place.

I'm wondering why we do the rounding... it looks wrong. Shouldn't be there something similar to what we're doing in binning https://github.com/NeuralEnsemble/elephant/blob/a6a085466f1d821cb9ef83c34db05a0f32e8f166/elephant/conversion.py#L822-L830?
