### ISSUE TITLE
[Bug] zscore(..., inplace=True) does not change the units of the original signal to dimensionless

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/elephant#384]
If `inplace=True`, the returned signal has dimensionless units, but the modified in-place signal has the original units.

**Comment by rgutzen** [comment]
The problem seems to arise in this line:
```
sig_normalized = sig.magnitude.astype(mean.dtype, copy=not inplace)
```
which is just a link to the asig object when `inplace` is True. However, the removal of the units is only done on the newly created asig object `sig_dimless`.
So, just adding the line
```
sig_normalized.units = pq.dimensionles
```
would fix the behavior.

**Comment by dizcza** [comment]
At the first glance, I also thought about this. But we cannot change the units of an analog signal:
```
ValueError: can not modify units of a view of a Quantity
```

**Comment by jpgill86** [comment]
This seems to be a way to forcibly overwrite a Quantity's units, but I haven't checked whether it breaks anything:
```python
sig_normalized._dimensionality = pq.dimensionless.dimensionality
```

**Comment by dizcza** [comment]
Let's ask @apdavison what he thinks about modifying the units of an analog signal in-place.

**Comment by dizcza** [comment]
@samuelgarcia maybe Samuel has an opinion?
