### ISSUE TITLE
[Feature] Move away from using deprecated nose for testing

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/elephant#408]
**Feature**
nose is deprecated, so it'll be good to move to another testing tool, perhaps py.test.

**Motivation**
nose is deprecated upstream (the last commit was in 2016.) and is also being deprecated in Fedora.

https://github.com/nose-devs/nose/commits/master

It is still in use here, though: in the CI script (and it's listed in the requirements file also).

https://github.com/NeuralEnsemble/elephant/blob/master/.travis.yml#L74

The website says:

https://nose.readthedocs.io/en/latest/

"Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2."

Deprecation of nose in Fedora: https://fedoraproject.org/wiki/Changes/DeprecateNose

**Alternatives**
py.test or nose2 (but nose2 doesn't seem to be at par with nose or py.test)

**Additional context**
On the Fedora build, I've used `py.test` to run the tests instead of the nosetests command, and that seems to work fine. However, I'm not well-versed enough with the code to know if there some nose-specific bits in there that will need to be migrated too.

**Comment by mdenker** [comment]
Dear sanjayankur31,
thanks for your feedback, that's indeed a very good suggestion to take up.
