### ISSUE TITLE
[Bug] estimate csd loses t_start information for iCSD methods

### ISSUE THREAD

**Issue by SimonRenner** [NeuralEnsemble/elephant#424]
**Description**
`estimate_csd` always returns an `AnalogSignal` object with `t_start=0` for iCSD methods. 

**To Reproduce**
```
>>> import numpy as np
>>> import quantities as pq
>>> from neo import AnalogSignal
>>> from elephant.current_source_density import estimate_csd
>>> lfp = AnalogSignal(np.random.rand(10, 2)*pq.V, sampling_rate=1*pq.Hz, t_start=3.5*pq.s)
>>> csd = estimate_csd(lfp, np.array([[1],[2]])*pq.um, method='StandardCSD')
>>> csd.t_start
array(0.) * s
>>> csd_kern = estimate_csd(lfp, np.array([[1],[2]])*pq.um, method='KCSD1D')
>>> csd_kern.t_start
array(3.5) * s
```

**Proposed fix**
The root seems to be in l.188 of `current_source_density.py`:
```
lfp = neo.AnalogSignal(np.asarray(lfp).T, units=lfp.units, sampling_rate=lfp.sampling_rate)
```
which, does not use `t_start` from the input (kernel methods do not have the issue because they do not redefine the input lfp).
Adding `t_start=lfp.t_start` in l.188 should fix the problem. Alternatively, one could perhaps replace the redefinition with `lfp=lfp.T` since that seems to be all it does but I am not sure I am correct in that thought.

**Comment by mdenker** [comment]
Hi Simon, thanks for the report, will have a look!
