### ISSUE TITLE
Extract SpikeTrain from AnalogSignal

### ISSUE THREAD

**Issue by rgerkin** [NeuralEnsemble/elephant#43]
@apdavison Is there a function for this yet?  I didn't see it in a brief search.  If not let me know if I should just contribute the old AnalogSignal.threshold_detection code from NeuroTools, and if so to what module (maybe a new module for AnalogSignal manipulations, which could subsume sta.py since it currently only has one function).

**Comment by apdavison** [comment]
No, there isn't a function for this yet; I'd be happy for you to adapt the code from NeuroTools. Not sure about the module. Maybe `spike_train_generation`?

In general, I'm not too worried at the moment about module naming, and where certain functions should go; I think this is a discussion to have once we have a larger number of functions implemented. At that point we can move things around.

**Comment by samuelgarcia** [comment]
You can also take code from 
https://github.com/OpenElectrophy/OpenElectrophy/tree/master/OpenElectrophy/spikesorting/detection
to port it to elephant.
There are several detection methods there.

**Comment by apdavison** [comment]
Excellent idea @samuelgarcia

**Comment by apdavison** [comment]
On looking at this a second time, are your modules for extracting spikes from extracellular recordings, @samuelgarcia ? I think @rgerkin is talking about the easier task of extracting spikes from intracellular recordings; perhaps we should provide both, although I'm not sure Elephant should tackle issues related to spike sorting, as there are already Python packages for that.

**Comment by samuelgarcia** [comment]
Intracellular spike detection is the most simple case of extra cellular spike detection : one electrode + absolut threshold.
The are two algo implemented about that in OpenElectrophy : one with threshold detection and one with peak detection above a threshold. Both are implemented in numpy style or numepxr.
See
https://github.com/OpenElectrophy/OpenElectrophy/blob/master/OpenElectrophy/spikesorting/detection/tools.py
This very simple codes that can be copy/paste/adapted.

**Comment by toddrjen** [comment]
@apdavison Yes, it seems like spike sorting is a big enough issue on its own to be outside the scope of elephant.  Having it work well with spike sorters makes sense, but I don't think spike sorting itself belongs in elephant.

**Comment by mdenker** [comment]
Yes, I agree, at least for now spike sorting is too big a topic for Elephant, in particular since spike sorting is also something that profits a lot from visualization.

**Comment by rgerkin** [comment]
@apdavison @samuelgarcia OK, I think I will just take it from NeuroTools to keep it simple.  And I will put it in `spike_train_generation` and update that module's docstring.  The OpenElectrophy version looks more powerful but there are more decisions to make if we want to use it.  For example, to avoid duplication would OpenElectrophy ever import elephant if some of the most basic single channel threshold detection algorithms are moved there?

**Comment by rgerkin** [comment]
I finished it and submitted the pull request, but Travis is failing at the virtualenv activation stage (before it gets anywhere near my code). @apdavison Any idea what's happening here?

**Comment by alperyeg** [comment]
@rgerkin the errors are partially a Travis problem, it can't initiate the virtual environment. After restarting the  jobs those errors will disappear in most of the cases (but can appear for certain builds again). 
But at the moment one of our unittests are broken, because of different library versions. I suggested a quick fix in a pull request (https://github.com/NeuralEnsemble/elephant/pull/46). If this will be merged you could update your pr and rerun the jobs.

**Comment by rgerkin** [comment]
@alperyeg OK, thanks. I'll keep an eye on it.

**Comment by rgerkin** [comment]
Working except for #54.
