### ISSUE TITLE
[Bug] Neo 0.10.0 SpiketrainList objects may not pass type checks

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/elephant#431]
**Describe the bug**
Some elephant functions check if an input is indeed a list of `neo.SpikeTrain` objects. With Neo 0.10.0, container objects such as `Segement` store lists of spiketrains as `SpikeTrainList` objects, and therefore users may pass such an object instead of a proper list. The error will be difficult to spot, therefore functions should make proper checks for lists of spike trains or a `SpikeTrainList` object.
An example of a function that checks inputs in this way is `spade.spade()`.

Workaround:
```python
x = [st for st in block.segment.spiketrains]
```

**Comment by morales-gregorio** [comment]
Hi! I can confrm @ackurth and I run into this problem when trying to use `elephant.conversion.BinnedSpikeTrain()`, would just avoiding the error already fix the issue or does the spiketrainlist also need special handling?

Best,
Aitor
