### ISSUE TITLE
discretise_spiketimes behavior and documentation

### ISSUE THREAD

**Issue by kohlerca** [NeuralEnsemble/elephant#464]
Hi everyone,

I noticed that the new `discretise_spiketimes` function (PR #454) replaces the generated `SpikeTrain` annotations `dict` with a reference to the `dict` in the original `SpikeTrain`, after the duplication with new data (line 1310). This will make any changes to the annotations in the original `SpikeTrain` to also change the annotations in the generated `SpikeTrain`, and vice-versa.

As this behavior is not clear, the code could make a brief explanation of the motivation as comments, and this could also be mentioned in the documentation so that it is apparent to the user. 

Alternatively, the line could be omitted from the code, as the Neo function already copies the annotations, and the benefit of having a reference to the original annotations is not clear.

Finally, the docstring of the function (or the module) would benefit from having a quick example showing what discretization does, similar to what is done for `BinnedSpikeTrain` in the module docstring.

**Comment by Kleinjohann** [comment]
Hi @kohlerca, thanks for noticing this! The referenced annotations are a bug, that was not intended.

Should the usage example go into the docstring of the module or into the docstring of the function itself?

**Comment by Moritz-Alexander-Kern** [comment]
Hi,
thanks for taking care of this @kohlerca and @Kleinjohann .

I would prefer to have the usage example in **the docstring of the function itself.** 
This will avoid clutter and overloaded docstrings for modules containing many functions in the future. Further I assume this is the place one would expect a usage example.
