### ISSUE TITLE
[Feature] Remove scipy version cap

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/elephant#470]
**Feature**

Would it be possible to remove the scipy version cap in requirements please? It's capped to `<1.7` but the current scipy release is now `1.8`, so that's quite old. We don't ship 1.7 in Fedora any more, for example, and the cap means it makes it hard to ship elephant too.

https://pypi.org/project/scipy/
https://packages.fedoraproject.org/pkgs/scipy/python3-scipy/

**Motivation**

I empathise with the need to add upper version bounds, but they seem to cause more issues than they solve. Here's a post listing issues it's causing in the Python ecosystem for example:

https://iscinumpy.dev/post/bound-version-constraints/

**Alternatives**

NA

**Additional context**

NA

**Comment by Moritz-Alexander-Kern** [comment]
Hi, thanks for pointing this out.
This was introduced here: https://github.com/NeuralEnsemble/elephant/pull/419/commits/1d295504f56183b96137554230c3ec0afb6b6006
PR #473 removes the version cap.
