### ISSUE TITLE
CNS*2022 satellite tutorial on Elephant

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/elephant#484]
Hi everyone,

The INCF/OCNS Software WG is organising a set of free online satellite tutorials ahead of CNS*2022 in the week of June 27--July 1.

Given how useful Elephant is, I was wondering what you thought of doing a session on Elephant too? (There's one planned on Neo/NWB also)

You can see the currently planned sessions etc here:

https://github.com/OCNS/SoftwareWG/milestone/3

The announcement post is here:

https://ocns.github.io/SoftwareWG/pages/software-wg-satellite-tutorials-at-cns-2022.html

**Comment by sanjayankur31** [comment]
Hello,

We're asking everyone for confirmation now---could you please confirm if you'd like to do a tutorial?

Thanks very much,

**Comment by mdenker** [comment]
Hi sanjayankur31,
thanks for pointing us there. We'd be very happy to contribute an Elephant tutorial for this event, which could range from a short demo to a full run-through of a combined Neo/Elephant analysis of a specific dataset. I've seen there is also a Neo proposal, so possibly, one could also combine the two given they are very close, and we have material covering both.

**Comment by mdenker** [comment]
Sadly, when asking around, I did not find someone who would be present do the tutorial also on-site, in case that is planned as an option.

**Comment by mdenker** [comment]
In case a mini abstract is useful, this would be roughly what we would have in mind -- depending on the length of the session:
```
In this workshop, we will explore how to represent and work with electrophysiological activity data containing spiking activity and local field potentials using the Neo data model, and how to perform a statistical analysis of such data using the Elephant framework. We will work with a fully publicly available electrophysiological dataset to walk-through a potential data analysis scenario step-by-step from loading the data to obtaining results on the statistical characterization of spiking activity using a series of prepared Jupyter notebooks.
```

**Comment by sanjayankur31** [comment]
Thanks very much.

Yes, there's a neo session planned too. Would it be possible for you to speak to @apdavison and @appukuttan-shailesh to see if you'd like to combine the elephant and neo/nwb session into one? If they're quite different, they can just be two different sessions---no problems there either.

In general, we think we will have three categories of sessions:

- short: 1.5--2 hours
- "half day": ~3 hours
- "full day": 6--7 hours

We leave the exact duration up to the different organisers.  With the sessions being online, we are extremely flexible :)

We are reaching out to all the organisers now for initial bits of information to help us get started on the schedule. Could you please tell us by the 20th (end of next week):

- what is the expected duration of the session?
- what is the preferred start time of the session (in UTC)?
- are there days that you *cannot* hold the session in the June 27--July 1 interval?
- would you like us to set up zoom meeting rooms for you (for organisers
  that may not have access to institutional zoom etc. subscriptions)?

If you can please set up a web-page for the session and give us the
link, we will put that on the schedule too. This last one is not necessary
just yet. It is also possible to set up a post on our website.

We are requesting organisers to record these sessions if possible, and
we will work with the INCF folks to get the recordings put up on the
INCF training space.


---

I think tutorial submissions for the on-site meeting have already closed. We're not really involved in those---the OCNS Tutorials Chair manages those because of the extra logistics required by an in-person meeting. 

---

The abstract sounds great. We can put that on the web-page with any other information.

**Comment by mdenker** [comment]
Great, thanks for the info. I assume, we'll be aiming for something between 2h and 3h slot, which in the past has been a good time frame. I'll get in touch with apdavison and provide you with the required info.

**Comment by Moritz-Alexander-Kern** [comment]
The schedule is now online here : https://ocns.github.io/SoftwareWG/pages/software-wg-satellite-tutorials-at-cns-2022.html .

Neo + Elephant tutorial will be on Friday, 1st July 2022, 9:00 - 12:00 CEST

**Comment by Moritz-Alexander-Kern** [comment]
Thanks again for the invitation.

**Comment by sanjayankur31** [comment]
@Moritz-Alexander-Kern @mdenker : thanks very much for the session. I'll send out an e-mail to all tutors about how things went and what we could do to make them better if we repeat them. 

Did you record the session by any chance, if yes, could you please send me the link? I'll put it on the public schedule and also try to get them all uploaded to the INCF training space.

**Comment by Moritz-Alexander-Kern** [comment]
hey, 
as far as i know this session was not recorded.

**Comment by sanjayankur31** [comment]
OK cool, no worries. I'll e-mail all tutors in the next few working days.
