### ISSUE TITLE
[Bug] Pip install fails on linux due to fim issue

### ISSUE THREAD

**Issue by jonahpearl** [NeuralEnsemble/elephant#506]
**Describe the bug**
After cloning the repo, `pip install -e .` fails with this error message:
[pip elephant error.txt](https://github.com/NeuralEnsemble/elephant/files/9182998/pip.elephant.error.txt)

I am using a compute cluster running Linux.

**To Reproduce**
1. Clone the repo 
2. Load gcc
3. Attempt to install

**Expected behavior**
Installs without issue

**Environment**
 -Linux: 3.10.0-1160.71.1.el7.x86_64
 - GCC 6.2.0
 - git clone 
 - Python version: 3.9.6
 - `neo` python package version: 0.10.2
 - `elephant` python package version: 0.12.0b1

Solved for now by preventing fim_module from being compiled in setup.py.

**Comment by Moritz-Alexander-Kern** [comment]
Hi @jonahpearl ,
thanks for reporting this issue.

PR #494 implements your solution by  adding an install option:

- development  `pip install -e . --install-option='--no-compile' `
- install `pip install elephant --install-option='--no-compile' `

For the future we plan to add a list of compatible compilers and their versions to the documentation.

You could also manually download the wheel (artifact) from the build wheel github action https://github.com/NeuralEnsemble/elephant/actions/runs/2733121938 and copy the compiled fim.so to `elephant/spade_src`.

Thanks again for reporting this.
