### ISSUE TITLE
Data conversion - BinnedSpikeTrain - fails

### ISSUE THREAD

**Issue by tompfeil** [NeuralEnsemble/elephant#53]
The following example in the elephant documentation fails:

    import elephant.conversion as conv
    import neo as n
    import quantities as pq
    st = n.SpikeTrain([0.5, 0.7, 1.2, 3.1, 4.3, 5.5, 6.7] * pq.s, t_stop=10.0 * pq.s)
    x = conv.BinnedSpikeTrain(st, num_bins=10, binsize=1 * pq.s, t_start=0 * pq.s)
    print(x.spike_indices)
    print(x.to_sparse_array().nonzero()[1])

Using latest development versions of python-neo (baf6562593e85a1c041408a57a2234e5febe652a) and elephant (83414608a3f45b51b291f1b7d48f55cd27b89bea):

    File "delme.py", line 5, in <module>
      x = conv.BinnedSpikeTrain(st, num_bins=10, binsize=1 * pq.s, t_start=0 * pq.s)
    File "/afsuser/tpfeil/elephant_inst/lib/python2.7/site-packages/elephant-0.2.0-py2.7.egg/elephant/conversion.py", line 424, in __init__
      self._convert_to_binned(spiketrains)
    File "/afsuser/tpfeil/elephant_inst/lib/python2.7/site-packages/elephant-0.2.0-py2.7.egg/elephant/conversion.py", line 794, in _convert_to_binned
      f, c = np.unique(filled_tmp, return_counts=True)
    TypeError: unique() got an unexpected keyword argument 'return_counts'

**Comment by alperyeg** [comment]
Which version of numpy do you use? Can you try to upgrade numpy to a version >= 1.9.0  and see if the error still exists?

**Comment by tompfeil** [comment]
This solves the problem, thanks!
