### ISSUE TITLE
Fix threshold_detection to handle signals with no spikes

### ISSUE THREAD

**Issue by rgerkin** [NeuralEnsemble/elephant#54]
If there are no spikes (no threshold crossing), `threshold_detection` returns a SpikeTrain that had undefined length, rather than length zero.  

See [here](https://gist.github.com/rgerkin/54aad46550c102b758bc)

I can fix this easily, but first I'm wondering if there is an upstream fix in Neo to disallow this kind of `SpikeTrain` (i.e. there appear to be two ways to generate a `SpikeTrain` with zero spikes, and only one of them seems legitimate; should the other one raise and error or be redirected to the legitimate one)?

**Comment by apdavison** [comment]
Neo should catch this. I've created a ticket in the Neo issue tracker: https://github.com/NeuralEnsemble/python-neo/issues/217

**Comment by alperyeg** [comment]
@rgerkin funny times with travis ci start again. Maybe the following error is linked to this issue here. 
Can you check `TypeError: len() of unsized object` which appears in `test/test_spike_train_generation.py", line 54, in test_threshold_detection`.
So far I could see the error occurs with python3.4 but not python2.7, conda build. 
But it worked before right?

Here is the travis log: 
https://travis-ci.org/NeuralEnsemble/elephant/jobs/86387377
https://travis-ci.org/NeuralEnsemble/elephant

**Comment by rgerkin** [comment]
@alperyeg There's at least two problems here.  One is the unsized spike train problem (which needs to be fixed in Neo, and caught in Elephant until then).  The other is that the unsized spike train usually means a zero-length spike train, which means the test will fail even when it is fixed, since the true spike train has 7 spikes in this test.  I'll look into this.

**Comment by rgerkin** [comment]
@alperyeg @apdavison OK, this is weird.  In trying to debug the issue, Travis is now failing to load numpy in Python 3.4.  It can't have anything to do with my changes, which are too cosmetic.  

https://travis-ci.org/neuroelectro/elephant
https://travis-ci.org/neuroelectro/elephant/jobs/86729943

Is this one of those things where I just run it again tomorrow and it works?

**Comment by alperyeg** [comment]
@rgerkin unfortunately not. This error appears with python3 and the latest version of numpy (v1.10.0) and quantities. I could run the `test_spiketrain_generation` module without errors if I changed line 56 
```python
assert np.allclose(spike_train, spike_train)
```  
to 
```python
assert np.array_equal(spike_train, spike_train)
```
That worked for me, can you test it out? But be aware that travis fails again, other test are also breaking, because of numpy, quantities (and python3).

**Comment by alperyeg** [comment]
I run some other tests, I even installed the same conda build (python3, numpy 1.8.1, scipy 0.14.0) on our cluster and run the test again, everything worked. But on travis the same error `len() of unsized object`  appears again.
I guess it is really something simple, but it is again hard to figure out.

**Comment by rgerkin** [comment]
@alperyeg OK, I added exception handling for older versions of numpy that don't have `np.allclose`.  But I am still getting the `numpy` import error in Travis for every Python 3 build.  Since the code works for both of us using Python 3 (and I don't even get the original Travis error with the empty spike train with my Python 3, nor do any of the Python 2 builds on Travis), I think we can chalk remaining issues up to Travis's python 3 environment.  

To clarify, I am talking about my fork, where I have already dealt with `len() of unsized object`.

**Comment by alperyeg** [comment]
There are some things I tried so far. I believe it is a build problem. I do not know why it appears now and not before, but the error comes when using the conda build with numpy 1.8.1, scipy 0.14.0 and python 3. The libfortran type error can be side stepped if we include `conda install libgfortran` in the install script. 
After doing this I could get an error that the spike train is a nan. 

Here is the error-log 
https://travis-ci.org/alperyeg/elephant/jobs/86843835
And here is my branch:
https://github.com/alperyeg/elephant/tree/fix/conversion

So far I had to modiy: 
* .travis.yml
* continuous_integration/install.sh
* elephant/conversion.py (not for this issue)
* elephant/signal_processing.py (not for this issue)
* elephant/test/test_spiketrain_generator.py 

When testing I am excluding pandas_bridge for the moment, this is an other issue (the last ubuntu build). 
I am pretty sure the nan error in test_spiketrain_generator.py will disappear with numpy 1.9, but I am trying to find out what happens here with the arrays. 

Hope this information could help a little bit.

**Comment by rgerkin** [comment]
I made those changes (also you misspelled fortran as fortan in .travis.yml, so I fixed that).  It works, so I'm addressing the spike train error now.

**Comment by rgerkin** [comment]
@alperyeg 
OK, so here is the problem:  In my current code (in `test_threshold_detection`) I have:  
```
time = signal.times
events = time[cutout][take]
print('Events length is %d' % len(events))
print('Events are ',events)
print('Events base is ',events.base)
```

In the Python 2 and 3 builds, the events length is 7 (i.e. spikes are extracted correctly) and the times are the same (both print `[ 0.0123  0.0354  0.0712  0.1191  0.1694  0.22    0.2711] s`).  But for some reason in Python 3 the `events.base` attribute is `None`, whereas in Python 2 it is just the event times without the units as expected.  So maybe `quantities` is incorrectly extracting the base values in Python 3?

I can't reproduce this in my Python 3 local build, but perhaps there is something about the Travis build where the version of quantities being used is incompatible with the version of numpy being used.  I am going to find a workaround for the `base` attribute and that should fix things until the deeper problem is better understood.

**Comment by rgerkin** [comment]
@alperyeg @apdavison OK, the issue is fixed completely on [my fork](https://travis-ci.org/neuroelectro/elephant).  Remaining Python 3 errors are on unrelated tests.  

The `base` attribute wasn't working with `quantities` arrays, but I just reconstructed the array like so:
`events_base = np.array([event.base for event in events])` instead of the simpler `events_base = events.base` which wasn't working in the Python 3 builds.  This workaround rebuilds the spike train times array element by element.  

I edited some of my files manually to add @alperyeg's changes, so when these commits are pulled in some of them (related to travis or the conda install script) they can be rewritten to make @alperyeg the author to give proper credit.  I only fixed the problem in the paragraph above, and the one related to catching unsized spike trains.

**Comment by alperyeg** [comment]
@rgerkin I tried your changes and it works fine now with my changes included. All builds except the last run through. Very nice. 
Now to the next issue :)

**Comment by alperyeg** [comment]
@rgerkin can you make a pull request with your changes incorporated?

**Comment by rgerkin** [comment]
@alperyeg OK, it's there.

**Comment by alperyeg** [comment]
@rgerkin is the problem solved now? If yes can you or shall I close this issue?

**Comment by rgerkin** [comment]
@alperyeg I believe so.
