### ISSUE TITLE
Remove annoying warnings

### ISSUE THREAD

**Issue by morales-gregorio** [NeuralEnsemble/elephant#567]
The function `round_binning_errors()` from `elephant/utils.py` raises the following warning:
```
warnings.warn(f'Correcting {num_corrections} rounding errors by '
              f'shifting the affected spikes into the following '
              f'bin. You can set tolerance=None to disable this '
              'behaviour.')
```

Which leads to *hundreds* of warnings being raised whenever trying to bin multiple spike trains. The behaviour is desired and I do not think that a warning is necessary, this behaviour is very well documented in the `elephant.conversion.BinnedSpikeTrain`.

I know @Kleinjohann wrote this correction, is this fine for you?

**Comment by Kleinjohann** [comment]
> I know @Kleinjohann wrote this correction, is this fine for you?

Fine by me, I agree that we shouldn't raise that many warnings.

**Comment by morales-gregorio** [comment]
Hi Moritz
 
> Just to clarify, does your comment also include the warning raised in the second if-clause at Line 298?
> 
> https://github.com/NeuralEnsemble/elephant/blob/c7b581422437b24828f429e2cc8ff88071c07654/elephant/utils.py#L288-L303

No, only lines 291-294, I never encountered the line 298 warning. 

As a note to the warning suppression, I usually do that, but it does not seem to work when multithreading, so the problem persists (and the warning is anyway expected behavior). 

Best,
Aitor
