### ISSUE TITLE
[Bug] Wheels for Python 3.11/3.12 missing from build

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/elephant#581]
The github action for building pre-compiled wheels should be enhanced to cover Python 3.11 and 3.12, which are currently not built. Possibly this could be solved by updating the version of cibuildwheels installed in the action.

**Comment by Moritz-Alexander-Kern** [comment]
Python 3.12.0 final is scheduled for Monday, 2023-10-02 (2nd Oct. 2023) , see: https://peps.python.org/pep-0693/
