### ISSUE TITLE
SpikeGLX data

### ISSUE THREAD

**Issue by taningh86** [NeuralEnsemble/elephant#618]
Hi,
I am assuming with healthy confidence that people have run elephant with neuropixels/spikeGLX data. Is there a tutorial or worked example for analyzing neuropixels data? I have used the spikeGLX specific NEO IO module but for some reason 'block' is not recognized or working. I wonder if I the bin files of spikeGLX don't have the structure Elephant wants and I need to do some processing to get to that. I will very much appreciate if anyone has any suggestions or solutions for this.

Thanks!

**Comment by Moritz-Alexander-Kern** [comment]
Hey @taningh86 ,
Thank you for reaching out to us. 

Elephant often works with `AnalogSignal` and `SpikeTrain` objects, and `Block` objects are not directly supported as input for Elephant functions.

If your data was loaded using a NEO IO, the structure is indeed supported by Elephant. In NEO, a Block typically contains Segment objects, and these Segment objects contain `AnalogSignal` and `SpikeTrain` objects, which are the types of data that Elephant works with.

For an overview of the Neo structure see also: https://neo.readthedocs.io/en/latest/read_and_analyze.html#dataset-structure

So, if you’re encountering issues with a Block object not being recognized, it might be because Elephant is expecting `AnalogSignal` or `SpikeTrain` objects instead. You might need to extract these from the Block object first before passing them to Elephant.

A tutorial which shows how to work with a `block` and how to use this with Elephant or more specifically how to extract spiketrains, can be found here: https://elephant.readthedocs.io/en/latest/tutorials/unitary_event_analysis.html 

The following information could help me to give a more precise answer:

Which Elephant functions are you using?

In which way is 'block' is not recognized or working? Do you get an error? If so could you provide the error message?

Which versions of Neo and Elephant are you using?

Is the neuropixels/spikeGLX data you are working with publicly available? In this case it would be possible to develop a tutorial or example for Elephant.

Can you provide an example code where the use of Elephant is not working? 



I hope this helps! Let me know if you have any other questions.

**Comment by taningh86** [comment]
Hi @Moritz-Alexander-Kern ! Thanks for the detailed response. Yes, soon after I posted this question I found out that the spikeGLX data needs to be converted to spiketrains. I was able to do so. below is the code I used to convert continuous data into spiketrains. I used the "spike_times.npy" file that kilosort 2.5 outputs to extract spiketrains.
```

`import numpy as np
from scipy.sparse import lil_matrix
import quantities as pq
import neo

# Load spike times and spike clusters
spike_times = np.load('G:/Cat_GT_Out/catgt_12_29_23_redo_ACA_LHA_24FAST_EXP_g0/results_KS25/sorter_output/spike_times_sec.npy')
spike_clusters = np.load('G:/Cat_GT_Out/catgt_12_29_23_redo_ACA_LHA_24FAST_EXP_g0/results_KS25/sorter_output/spike_clusters.npy')

bin_size = 1  # Adjust the bin size as needed
chunk_size = 5000  # Choose a reasonable chunk size based on your available memory and processing requirements

# Downsample spike times
downsample_factor = 10  # Adjust as needed
spike_times = spike_times[::downsample_factor]
spike_clusters = spike_clusters[::downsample_factor]

# Update the total duration based on the original recording duration
original_duration = 1820.97  # Replace with the actual duration of your original dataset in seconds
duration = original_duration + bin_size  # Add bin_size to ensure the last bin is included

# Initialize sparse matrix
num_neurons = len(np.unique(spike_clusters))
total_bins = int(duration / bin_size)
spike_counts = lil_matrix((num_neurons, total_bins), dtype=np.uint32)

# Initialize variables for the total duration and spike counts
total_duration = 0
total_spike_counts = lil_matrix((num_neurons, 0), dtype=np.uint32)

# Process data in chunks
for start_index in range(0, len(spike_times), chunk_size):
    end_index = start_index + chunk_size
    chunk_spike_times = spike_times[start_index:end_index]
    chunk_spike_clusters = spike_clusters[start_index:end_index]

    # Initialize sparse matrix for the current chunk
    num_neurons = len(np.unique(chunk_spike_clusters))
    chunk_duration = chunk_spike_times[-1] - chunk_spike_times[0] + bin_size
    chunk_spike_counts = lil_matrix((num_neurons, int(chunk_duration / bin_size)), dtype=np.uint32)

    # Process data in the current chunk
    for neuron_id in range(num_neurons):
        neuron_mask = (chunk_spike_clusters == neuron_id)
        neuron_spike_times = chunk_spike_times[neuron_mask]

        # Use np.digitize to find bin indices for each spike time
        bin_indices = np.digitize(neuron_spike_times, bins=np.arange(chunk_spike_times[0], chunk_spike_times[-1], bin_size))

        # Update chunk_spike_counts using bin indices
        for i in range(len(neuron_spike_times)):
            bin_index = bin_indices[i] - 1
            chunk_spike_counts[neuron_id, bin_index] += 1

    # Append chunk_spike_counts to the total_spike_counts
    total_spike_counts = lil_matrix((num_neurons, total_spike_counts.shape[1] + chunk_spike_counts.shape[1]), dtype=np.uint32)
    total_spike_counts[:, -chunk_spike_counts.shape[1]:] = chunk_spike_counts

    # Update the total duration
    total_duration += chunk_duration

# Convert total_spike_counts to a list of SpikeTrains
spike_trains = []
for i in range(num_neurons):
    spike_indices = np.where(total_spike_counts[i].toarray())[1]
    spike_indices = spike_indices[spike_indices <= total_duration / pq.ms]
    neuron_spike_train = neo.SpikeTrain(spike_indices, units='ms', t_stop=total_duration)
    spike_trains.append(neuron_spike_train)

```
# Now you have spike_trains ready for further analysis`

However, I am not sure if the last part of my code is accurate in the sense that, it is making spiketrains of the whole 30 min long recording, which is a lot. With a bin size = 1, chunk = 5000, and downsampling by a factor of 10 I was able to get there. But in reality I would like the binsize to be about 1ms and not downsample my data. When I do that I get "memory read error" saying that the computer is unable to allocate required memory for that. Could you let me know what should I do, in terms of making individual spiketrains chunks and then going with downstream analysis or building spiketrains with all chunks in one shot, like I have done here? I am just not sure about this.

- As for now I am using ASSET but there are many analysis concepts in elephant that I am certainly going to use.
- YES!! It will be excellent if a tutorial could be made for spikeglx data. I won't hesitate to share data but spikeglx data is publicly available in the following link.
- https://dandiarchive.org/dandiset/000053/0.210819.0345/files?location=sub-npI1%2F
- Also, below is options to download publicly available dataset from Allen brain institute https://allensdk.readthedocs.io/en/latest/_static/examples/nb/ecephys_data_access.html
 
Please let me know how can I assist more in this process of developing a tutorial for neuropixels data.

Thanks!
Jimmy

**Comment by Moritz-Alexander-Kern** [comment]
Hey @taningh86 !

I understand that you're working on loading the Kilosort output, which consists of 2 numpy arrays (`spike_times_sec.npy`and `spike_clusters.npy`), and you're trying to convert them into Neo `SpikeTrains`.

Firstly, there might be a Neo IO (Input/Output) module that can assist you with this conversion. You can try using the `neo.io.get_io` function, which can help you guess the correct IO module from Neo. You can find more information about it in the Neo documentation here: https://neo.readthedocs.io/en/latest/iolist.html#neo.io.get_io .

Alternatively, you can explore the available raw IOs in Neo. These raw IOs can also be found in the Neo documentation, here: https://neo.readthedocs.io/en/latest/rawiolist.html#module-neo.rawio. They might provide a more automated way to handle the conversion, saving you from doing it manually.

If these options don't fully address your needs, I recommend reaching out to the Neo team for assistance. You can create an issue on their GitHub repository. Since this repository focuses on Elephant and I'm an Elephant developer, the Neo Issue board might be a better place to ask your question, see https://github.com/NeuralEnsemble/python-neo/issues . There are experts who can guide you on loading data in different formats to use with Neo or suggest the best way to load Kilosort output.

Otherwise consider to utilize the Neo objects for creating a list of Spiketrains, in contrast to a Python list, neos `SpikeTrainList` allows you to store spike trains memory efficient.

i.e.

```python
from neo.core import Segment, SpikeTrain
import numpy as np
from quantities import ms


# Load the spike times and spike clusters from the Kilosort output files
spike_times = np.arange(100)
spike_clusters = np.random.randint(1, 4, size=100)

# Get the unique cluster IDs (i.e., the neuron IDs)
unique_clusters = np.unique(spike_clusters)

# Create a Segmen to hold the spike trains for each neuron
segment = Segment()

# For each unique cluster (neuron), create a SpikeTrain object
for cluster in unique_clusters:
    # Get the spike times for this cluster
    cluster_spike_times = spike_times[spike_clusters == cluster]
    
    # Create a SpikeTrain object for this cluster
    segment.spiketrains.append(SpikeTrain(cluster_spike_times * ms, t_stop=cluster_spike_times.max()))

# Now, segment.spiketrains is a list where each element is a SpikeTrain object corresponding to a neuron
print(segment.spiketrains)
```

I hope these suggestions help you in your task. Good luck, and feel free to ask if you have any further questions!

**Comment by taningh86** [comment]
Hi Moritz! Thank you very much for a detailed response. I will did into the details that neo have with spikeGLX data and see what options they have. In the meantime your code looks good and I am hoping it will run some of the analysis in Elephant. Thanks again!

**Comment by taningh86** [comment]
Hi Moretz. I am starting to suspect if ASSET has a specific way of identifying clusters ID. Below is the code I used to generate spiketrains list and you can see that I also made sure if it is going through all unique clusters.
from neo import SpikeTrain. 
```

# Load spike times and spike clusters
spike_times = np.load('G:/Cat_GT_Out/catgt_12_29_23_redo_ACA_LHA_24FAST_EXP_g0/results_KS25/sorter_output/spike_times_sec.npy')
spike_clusters = np.load('G:/Cat_GT_Out/catgt_12_29_23_redo_ACA_LHA_24FAST_EXP_g0/results_KS25/sorter_output/spike_clusters.npy')

# Assuming t_stop is the total duration of your recording
t_stop = np.max(spike_times)

# Get the unique cluster IDs (i.e., the neuron IDs)
unique_clusters = np.unique(spike_clusters)

# Create a Segment to hold the spike trains for each neuron
segment = Segment()

# For each unique cluster (neuron), create a SpikeTrain object with a unique ID
# For each unique cluster (neuron), create a SpikeTrain object with a unique ID
for cluster_id in unique_clusters:
    print("Processing cluster_id:", cluster_id)
    
    # Get the spike times for this cluster
    cluster_spike_times = spike_times[spike_clusters == cluster_id]

    # Create a SpikeTrain object for this cluster with a unique ID (e.g., cluster_id)
    spike_train = SpikeTrain(cluster_spike_times, t_stop=t_stop, units='s', name=str(cluster_id))

    # Add the SpikeTrain to the Segment
    segment.spiketrains.append(spike_train)
```
I get the following output for checking if all unique clusters are being processed 
Processing cluster_id: 0
Processing cluster_id: 1
Processing cluster_id: 2
Processing cluster_id: 3
Processing cluster_id: 4
Processing cluster_id: 5
Processing cluster_id: 6
Processing cluster_id: 7
Processing cluster_id: 8
Processing cluster_id: 9
Processing cluster_id: 10
Processing cluster_id: 11
Processing cluster_id: 13
Processing cluster_id: 14
Processing cluster_id: 15
Processing cluster_id: 16
Processing cluster_id: 17
Processing cluster_id: 18
Processing cluster_id: 19
Processing cluster_id: 20
Processing cluster_id: 21
Processing cluster_id: 22
Processing cluster_id: 23
Processing cluster_id: 24
Processing cluster_id: 25
Processing cluster_id: 26
Processing cluster_id: 27
Processing cluster_id: 28
Processing cluster_id: 29
Processing cluster_id: 30
Processing cluster_id: 31
Processing cluster_id: 32
Processing cluster_id: 33
Processing cluster_id: 34
Processing cluster_id: 35
Processing cluster_id: 36
Processing cluster_id: 37
Processing cluster_id: 38
Processing cluster_id: 39
Processing cluster_id: 40
Processing cluster_id: 41
Processing cluster_id: 42.....
processing cluster_id: 170

But running ASSET using the code below I get a plot that has Neuron ID in the intersection matrix from 0-1700 instead of 0-170. Not sure what's going on besides that the range is multiplied by a factor of 10. 
```
neuron_ids = [int(spike_train.name) for spike_train in segment.spiketrains]
asset_obj = ASSET(segment.spiketrains, bin_size=1000 * pq.ms)

# Compute the intersection matrix
imat = asset_obj.intersection_matrix()

# Plot the intersection matrix
plt.matshow(imat)
plt.colorbar()
plt.xlabel('Neuron ID')
plt.ylabel('Neuron ID')
plt.title('Intersection Matrix')
plt.show()
```
below is the plot. Could you please confirm me if its not an issue with ASSET not identifying the unique clusters?
<img width="576" alt="ASSET intersection matrix" src="https://github.com/NeuralEnsemble/elephant/assets/95593601/9c4b3185-2a04-43b1-bce5-5dc823bfa553">

**Comment by taningh86** [comment]
Hi Moritz,
I have found that the issue with the Neuron ID range in the plot is due to bin_size in ASSET. I am not sure why is that. For example, if I use bin_size = 10 * pq.s intead of bin_size = 1000 * pq.ms I get the correct range in the plot as shown below. This should not be the case, right?
<img width="576" alt="ASSET intersection matrix 1" src="https://github.com/NeuralEnsemble/elephant/assets/95593601/8cfe52b0-37c9-44b1-be11-2cbc028437e0">

**Comment by Moritz-Alexander-Kern** [comment]
Hey @taningh86 ,

To my understanding ASSET is behaving correctly, and the axis should indeed represent the bins rather than the neurons. The intersection matrix shows where these bins intersect.

See also: https://elephant.readthedocs.io/en/latest/reference/_toctree/asset/elephant.asset.asset.ASSET.html#elephant.asset.asset.ASSET.intersection_matrix
> 
> Generates the intersection matrix from a list of spike trains.
> 
> Given a list of neo.SpikeTrain, consider two binned versions of them differing for the starting and ending times of the binning: t_start_x, t_stop_x, t_start_y and t_stop_y respectively (the time intervals can be either identical or completely disjoint). Then calculate the intersection matrix M of the two binned data, where M[i,j] is the overlap of bin i in the first binned data and bin j in the second binned data (i.e., the number of spike trains spiking at both bin i and bin j).

But I have to admit I'm not an expert on ASSET and open to clarification on this point. :+1:

**Comment by taningh86** [comment]
Hi Moritz,
May be I am not understanding ASSET correctly. I will read up the paper and go into detail. 
So, considering the spiketrains that I am generating is a correct format then I would imagine it should work with many analysis pipelines in Elephant where spiketrains are used as an input, for example, UEA, SPADE etc.?

**Comment by taningh86** [comment]
Actually, for UEA the tutorial that is there uses spike train data from multiple trials of two neurons. This is different then my spiketrains. The spiketrain I generated is from one multisite recording containing ~170 units or supposed neurons. But, I am expecting UEA module to work for my dataset as well (may be with some tweaking) because it's mentioned in the description.
```The Unitary Events (UE) analysis [1] tool allows us to reliably detect correlated spiking activity that is not explained by the firing rates of the neurons alone. It was designed to detect coordinated spiking activity that occurs significantly more often than predicted by the firing rates of the neurons. **The method allows one to analyze correlations not only between pairs of neurons but also between multiple neurons,** by considering the various spike patterns across the neurons```
Could you suggest me ways to adapt my spiketrains for UEA?

**Comment by taningh86** [comment]
Below is the code I used to generate spiketrains that works with the Unitary event analysis. However I am getting error that says plot_ue is not defined (shown below).
Here's the code:
```from neo.core import SpikeTrain
import numpy as np
import quantities as pq
from quantities import ms
from itertools import combinations
import elephant.unitary_event_analysis as ue
import matplotlib.pyplot as plt

# Load the spike times and spike clusters from the Kilosort output files
spike_times = np.load('G:/Cat_GT_Out/catgt_12_29_23_redo_ACA_LHA_24FAST_EXP_g0/results_KS25/sorter_output/spike_times_sec.npy')
spike_clusters = np.load('G:/Cat_GT_Out/catgt_12_29_23_redo_ACA_LHA_24FAST_EXP_g0/results_KS25/sorter_output/spike_clusters.npy')

# Assuming t_stop is the total duration of your recording
t_stop = np.max(spike_times)

# Get the unique cluster IDs (i.e., the neuron IDs)
unique_clusters = np.unique(spike_clusters)

# Create a list to store SpikeTrain objects for each cluster
spiketrains_list = []

# For each unique cluster (neuron), create a SpikeTrain object and add it to the list
for cluster in unique_clusters:
    # Get the spike times for this cluster
    cluster_spike_times = spike_times[spike_clusters == cluster]
    
    # Create a SpikeTrain object for this cluster and add it to the list
    spiketrains_list.append(SpikeTrain(cluster_spike_times * pq.s, t_stop=t_stop))

# Perform unitary event analysis using Elephant
UE = ue.jointJ_window_analysis(
    [spiketrains_list], bin_size=5 * pq.ms, win_size=100 * pq.ms, win_step=10 * pq.ms, pattern_hash=[3]
)
plot_ue([spiketrains_list], UE, significance_level=0.05)
plt.show()```

And, below is the error:
```NameError                                 Traceback (most recent call last)
Cell In[16], line 34
     30 # Perform unitary event analysis using Elephant
     31 UE = ue.jointJ_window_analysis(
     32     [spiketrains_list], bin_size=5 * pq.ms, win_size=100 * pq.ms, win_step=10 * pq.ms, pattern_hash=[3]
     33 )
---> 34 plot_ue(UE, significance_level=0.05)
     35 plt.show()

NameError: name 'plot_ue' is not defined```

Any suggestions?

**Comment by taningh86** [comment]
And, below is the error.
```NameError                                 Traceback (most recent call last)
Cell In[16], line 34
     30 # Perform unitary event analysis using Elephant
     31 UE = ue.jointJ_window_analysis(
     32     [spiketrains_list], bin_size=5 * pq.ms, win_size=100 * pq.ms, win_step=10 * pq.ms, pattern_hash=[3]
     33 )
---> 34 plot_ue(UE, significance_level=0.05)
     35 plt.show()

NameError: name 'plot_ue' is not defined'''

**Comment by taningh86** [comment]
Any suggestions?

**Comment by Moritz-Alexander-Kern** [comment]
Hey @taningh86 ,

yes the `plot_ue` function is not defined.

See here for the complete notebook including the `plot_ue` function:

https://github.com/INM-6/elephant/blob/master/doc/tutorials/unitary_event_analysis.ipynb

**Comment by taningh86** [comment]
Oh ok. I thought plot_ue is already a defined function in 'ue'. I just followed the tutorial on the page https://elephant.readthedocs.io/en/latest/tutorials/unitary_event_analysis.html

**Comment by Moritz-Alexander-Kern** [comment]
Hey @taningh86 ,

the `plot_ue` function is also defined in viziphant, see: https://viziphant.readthedocs.io/en/latest/toctree/unitary_event_analysis/viziphant.unitary_event_analysis.plot_ue.html#viziphant.unitary_event_analysis.plot_ue

i.e. 

```python
import viziphant

viziphant.unitary_event_analysis.plot_ue(spiketrains, Js_dict, significance_level=0.05, **plot_params)
``

**Comment by Moritz-Alexander-Kern** [comment]
It seems all questions have been answered.
Feel free to re-open if needed.
