### ISSUE TITLE
[Bug] Spike waveform extraction error

### ISSUE THREAD

**Issue by smalsmal** [NeuralEnsemble/elephant#623]
**Describe the bug**
Hi, I'm trying to retrieve spike wave forms with the spike extraction function after finding spike times with the peak_detection function, but I keep on running into this error more or less consistently and don't know how to deal with it. In some cases (i.e. with some recordings) I seem to be able to "avoid" the error either by applying a more stringent spike detection threshold or by decreasing the wave start/stop time range. However, this is an issue, because I'm struggling to find a detection threshold and wave time range that would work with all of my recordings. From the errors sensitivity to the detection threshold and time range I would guess that the issue is with either n of spikes or overlapping of spikes, but maybe it isn't because sometimes it works perfectly fine with >3000 spikes and then gives me the error when there are <50 spikes (or vice versa). I would appreciate any help with this issue!

**To Reproduce**
1. 
2.

Traceback (most recent call last):

[103] result = ep.spike_train_generation.spike_extraction(Sig,  time_stamps=times, interval=(wave_start*ms, wave_stop*ms))
File [c:\Hyapp\Anaconda3-2023.07-2\envs\ephys_analysis\lib\site-packages\elephant\spike_train_generation.py:179](file:///C:/Hyapp/Anaconda3-2023.07-2/envs/ephys_analysis/lib/site-packages/elephant/spike_train_generation.py:179), in spike_extraction(signal, threshold, sign, time_stamps, interval)
    [173](file:///C:/Hyapp/Anaconda3-2023.07-2/envs/ephys_analysis/lib/site-packages/elephant/spike_train_generation.py:173)     waveforms = np.delete(waveforms, to_delete, axis=0)
    [174](file:///C:/Hyapp/Anaconda3-2023.07-2/envs/ephys_analysis/lib/site-packages/elephant/spike_train_generation.py:174)     warnings.warn("Waveforms " +
    [175](file:///C:/Hyapp/Anaconda3-2023.07-2/envs/ephys_analysis/lib/site-packages/elephant/spike_train_generation.py:175)                   ("{:d}, " * len(to_delete)).format(*to_delete) +
    [176](file:///C:/Hyapp/Anaconda3-2023.07-2/envs/ephys_analysis/lib/site-packages/elephant/spike_train_generation.py:176)                   "exceeded signal and had to be deleted. " +
    [177](file:///C:/Hyapp/Anaconda3-2023.07-2/envs/ephys_analysis/lib/site-packages/elephant/spike_train_generation.py:177)                   "Change 'interval' to keep.")
...
--> [394](file:///C:/Hyapp/Anaconda3-2023.07-2/envs/ephys_analysis/lib/site-packages/quantities/quantity.py:394)     ret = super().__getitem__(key)
    [395](file:///C:/Hyapp/Anaconda3-2023.07-2/envs/ephys_analysis/lib/site-packages/quantities/quantity.py:395)     if isinstance(ret, Quantity):
    [396](file:///C:/Hyapp/Anaconda3-2023.07-2/envs/ephys_analysis/lib/site-packages/quantities/quantity.py:396)         return ret

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed -->

**Expected behavior**
I would expect the spike_extraction to extract spike wave forms, when the input is a signal and spike times previously detected with the peak_detection function, irrespective of the spike detection threshold applied in the peak_detection and/or wave form interval.

**Environment**
 - OS (e.g., Linux): Windows 10
 - How you installed elephant (`conda`, `pip`, source): pip
 - Python version: 3.9.18
 - `neo` python package version: 0.12.0
 - `elephant` python package version: 1.0.0
 - (Any additional python package you want to include here)

**Comment by Moritz-Alexander-Kern** [comment]
Hey @smalsmal ,
Thanks for reaching out to us :+1: 

This could be similar to this: https://github.com/NeuralEnsemble/elephant/issues/613#issuecomment-1888724116

You can test if this fix implemented for the above works for your case by installing Elephant directly from this commit with pip:

```bash
pip install git+https://github.com/INM-6/elephant.git@1bd97ce2e768a8dcb3a522ff17742338308fe2d7
```

**Comment by smalsmal** [comment]
Hi @Moritz-Alexander-Kern, thank you for the response, unfortunately the suggested fix didn't help me, but I was able to fix my issue by modifying this part of the code:

    # len(np.shape(waveforms)) == 1 if waveforms do not have the same width.
    # this can occur when extraction interval indexes beyond the signal.
    # Workaround: delete spikes shorter than the maximum length with
    if len(np.shape(waveforms)) == 1:
        max_len = max(len(waveform) for waveform in waveforms)
        to_delete = np.array([idx for idx, x in enumerate(waveforms)
                              if len(x) < max_len])
        waveforms = np.delete(waveforms, to_delete, axis=0)
        warnings.warn("Waveforms " +
                      ("{:d}, " * len(to_delete)).format(*to_delete) +
                      "exceeded signal and had to be deleted. " +
                      "Change 'interval' to keep.")

    waveforms = waveforms[:, np.newaxis, :]

By retrieving the waveforms again after deleting those spikes, which exceed the signal.

    # len(np.shape(waveforms)) == 1 if waveforms do not have the same width.
    # this can occur when extraction interval indexes beyond the signal.
    # Workaround: delete spikes shorter than the maximum length with
    if len(np.shape(waveforms)) == 1:
        max_len = max(len(waveform) for waveform in waveforms)
        to_delete = np.array([idx for idx, x in enumerate(waveforms)
                              if len(x) < max_len])

        #Find spikes again after identifying the index to be removed
        borders_left = np.delete(borders_left, to_delete)
        borders_right = np.delete(borders_right, to_delete)
        borders = np.dstack((borders_left, borders_right)).flatten()

        waveforms = np.array(
        np.split(np.array(signal), borders.astype(int))[1::2]) * signal.units

        # Remove the index also from the spike times
        un = time_stamps.units
        time_stamps = np.delete(time_stamps, to_delete) * un

        #waveforms = np.delete(waveforms, to_delete, axis=0)
        warnings.warn("Waveforms " +
                      ("{:d}, " * len(to_delete)).format(*to_delete) +
                      "exceeded signal and had to be deleted. " +
                      "Change 'interval' to keep.")
    waveforms = waveforms[:, np.newaxis, :]

**Comment by Moritz-Alexander-Kern** [comment]
Hey [smalsmal](https://github.com/smalsmal),

I understand you resolved this, that's good news.

I will close this know unless there are further questions or points, if so, feel free to reopen this at any time.
