### ISSUE TITLE
GPFA update R in M-step, correctly forced diagonal?

### ISSUE THREAD

**Issue by ybernaerts** [NeuralEnsemble/elephant#640]
Hi guys,

I was surprised to see at
line 279 in module  gpfa_core.py : `params['R'] = np.diag(r[:, 0])`. But shouldn't this be `np.diag(np.diag(r))`, in order to extract all diagonal elements first, and put zeros on the offdiagonal? I think this would be correct according to equation A9 in [the original paper](https://journals.physiology.org/doi/epdf/10.1152/jn.90941.2008). Right now we seem to put all first-column elements on the diagonal, and zeros on the offdiagonal. Perhaps, however, the calculation is done differently in the code than I understand, so happy to receive feedback.

Best,
Yves

**Comment by ybernaerts** [comment]
I just noticed that the diagonal elements of R are also immediately available in the 1st column of r in this calculation. So, even though it's perhaps confusing, it seems correct. `np.diag(np.diag(r)) `here gives the same as `np.diag(r[:, 0])` .

**Comment by Moritz-Alexander-Kern** [comment]
Hi Yves,
I wasn't fast enough to react, but it's great to see this issue resolved. 

Thanks for your quick clarification that this is resolved.

Please feel free to reach out to us again any time, I think this exchange is beneficial for everybody.
