### ISSUE TITLE
about maxwell data

### ISSUE THREAD

**Issue by bxy666666** [NeuralEnsemble/elephant#642]
**Questions and Help**

_Please note that this issue tracker is not a help form and this issue may be closed and redirected to a more appropriate communication channel. Before asking a new question, please check our [NeuralEnsembe forum](https://groups.google.com/forum/#!forum/neuralensemble), where you can discuss any NeuralEnsemble resource, including Elephant._

Hello, I hope your help. I want to use maxwell data (H5 file）,how can I do? for example    UE = ue.jointJ_window_analysis(
    spiketrains, bin_size=5*pq.ms, win_size=100*pq.ms, win_step=10*pq.ms, pattern_hash=[3])

plot_ue(spiketrains, UE, significance_level=0.05)
plt.show()?????

**Comment by Moritz-Alexander-Kern** [comment]
Hey @bxy666666 , 
It looks like you're trying to use Maxwell data, which will require the Neo I/O modules. Neo is the right place to look for loading and handling H5 files. 

I also see that you've already opened an issue on the Neo issue tracker, here:
https://github.com/NeuralEnsemble/python-neo/issues/1570

I'll go ahead and close this here, as this should be discussed on the neo side. 
Thanks for reaching out, and good luck with your project!
