### ISSUE TITLE
Create conda package

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/elephant#66]
and put on binstar

**Comment by alperyeg** [comment]
called now [anaconda.org](http://anaconda.org)
docs are [here](http://conda.pydata.org/docs/build_tutorials/pkgs.html) and [here](http://docs.anaconda.org/using.html#Packages).

**Comment by alperyeg** [comment]
For testing purposes I made an anaconda package for elephant. Have a look here: 
https://anaconda.org/Alper/elephant

**Comment by Moritz-Alexander-Kern** [comment]
Closed, feel free to reopen at any time.
