### ISSUE TITLE
NumPy/SciPy versions installed in Travis are not always as requested 

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/elephant#70]
For some of the entries in the Travis matrix, the versions of `numpy` and `scipy` that end up being installed are not the same as the versions requested by the environment variables in `.travis.yml`

e.g.:

`DISTRIB="ubuntu"`: `NUMPY_VERSION="1.6.2" PANDAS_VERSION="0.16.0"`

What ends up being installed is `numpy 1.10.4`, `scipy 0.17.0`. The later version of Numpy is being pulled in by Pandas, Scipy by Elephant itself.

`DISTRIB="conda_min" NUMPY_VERSION="1.6.2" SCIPY_VERSION="0.11.0"`

We get `numpy 1.10.2`, `scipy 0.16.1`, which are pulled in by installing the `mkl` package.

`DISTRIB="conda" NUMPY_VERSION="1.9.0" SCIPY_VERSION="0.16.0" PANDAS_VERSION="0.16.0"`

We get `numpy 1.10.2`, `scipy 0.16.1`, again pulled in by `mkl`.

**Comment by alperyeg** [comment]
@apdavison can we close the issue?
