### ISSUE TITLE
Aliases for commonly-used functions from other scientific Python packages

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/elephant#8]
There are many Python packages dealing with time series analysis, which provide functions that may be of use to neuroscientists.

For an individual user, finding and identifying the functions of interest among multiple packages will be difficult. Furthermore, some (most) of these functions will not handle Neo objects or even units.

For functions which need to be adapted to handle Neo objects/units, it seems obvious that Elephant should provide wrappers. The question is whether we should also provide wrappers /aliases for functions that do not need to be adapted. An example of the latter is `scipy.stats.variation()`, for which I added an alias `cv()`(coefficient of variation), as I think the latter name will be much more obvious to neuroscientists.

The arguments for providing aliases are:

(1) providing all the functions of interest to neuroscientists in a single namespace;
(2) giving function names that are more familiar to neuroscientists.

**Comment by dizcza** [comment]
Obsolete.
If a function is needed, a dedicated issue should be opened.
