### ISSUE TITLE
ASSET conditional import and read the docs

### ISSUE THREAD

**Issue by mdenker** [NeuralEnsemble/elephant#88]
The import of sklearn breaks the readthedoc build for the asset.py page.

Probably we should import using something like

```python
try
    import sklearn
except:
   warning("sklearn not available).
```

to circumvent the problem.

**Comment by apdavison** [comment]
Or we could add sklearn to `environment.yml`

**Comment by mdenker** [comment]
Good point, that's easier -- I'll integrate it later and update the repo.
