### ISSUE TITLE
Implementing waveform extraction

### ISSUE THREAD

**Issue by danielmuellernai** [NeuralEnsemble/elephant#89]
Hello Neuronal Ensemble,

I've been working on a function that takes an AnalogSignal as input, finds spikes by threshold and returns a SpikeTrain object of the spike peaks. I also want to extract the waveforms of each spike in an interval around the peak but I am confused about the usage of SpikeTrain.waveforms.
By the neo doc: waveforms: (quantity array 3D (spike, channel_index, time)) The waveforms of each spike.
Therefore my .waveforms attribute has the shape (n, 1, i), where n is the number of spikes, 1 is just 1 because I have only 1 AnalogSignal and i is the extraction interval passed to the function. Is that the intended use of .waveforms?

Thanks,
Daniel

**Comment by rgerkin** [comment]
Shouldn't `time` be a range of time relative to the location of the spike in the train?

**Comment by apdavison** [comment]
I think this is best answered by @samuelgarcia, but my understanding is that you are correct. The reason for it being 3D is that with multielectrode recordings it is possible to have a spike recorded on more than one channel, but in the case of intracellular recordings or simulations there will only ever be a single channel.

**Comment by danielmuellernai** [comment]
That is a good hint, @apdavison, I did not consider that multielectrode recordings can contain the same spike in different channels.
@rgerkin, `time` is a time range in my implementation. Specifically, each element of `time` is a sampling point of the waveform.
