### ISSUE TITLE
Error on accessing `bin_edges` of `BinnedSpikeTrain`

### ISSUE THREAD

**Issue by btel** [NeuralEnsemble/elephant#90]
When trying to access the `bin_edges` property of `BinnedSpikeTrain` object the following error occurs:

```
Traceback (most recent call last):
  File "test_elephant.py", line 14, in <module>
    edges = binned.bin_edges
  File "/home/bartosz/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/elephant-0.3.0-py3.4.egg/elephant/conversion.py", line 585, in bin_edges
    self.num_bins + 1, endpoint=True),
  File "/home/bartosz/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/numpy/core/function_base.py", line 125, in linspace
    return y.astype(dtype, copy=False)
TypeError: astype() got an unexpected keyword argument 'copy'
```

The error can be reproduced with the following script:

```python
from elephant.conversion import BinnedSpikeTrain
import neo
from quantities import ms
import numpy as np

spiketimes = np.arange(10)*10
tmax = spiketimes.max()

spiketrain = neo.SpikeTrain(spiketimes * ms, t_stop=tmax * ms)
binned = BinnedSpikeTrain(spiketrain, t_start=0 * ms, binsize=50*ms)
edges = binned.bin_edges
```

It appears in python 3.44, with master branch of Elephant and neo, quantities 0.11.1 and numpy 1.11.0 (I think it does not occur with earlier version of numpy).

The problem is with the following with [conversions.py:L584](https://github.com/NeuralEnsemble/elephant/blob/master/elephant/conversion.py#L584)

```python
        return pq.Quantity(np.linspace(self.t_start, self.t_stop,
                                       self.num_bins + 1, endpoint=True),
                           units=self.binsize.units)
```

It seems that `numpy.linspace` returns a quantity object when `t_start` and `t_stop` are also quantity objects. Contrary to what the docstring says the `Quantity.astype` method does not take `copy` parameters (`numpy.astype` does). The workaround is to use `t_start` and `t_stop` without their units:

```python
np.linspace(self.t_start.magnitude, self.t_stop.magnitude,
                                       self.num_bins + 1, endpoint=True)
```

This bug was first spotted by @medelero

**Comment by alperyeg** [comment]
Thank you @btel I am creating a new pull request fixing this issue.
