### ISSUE TITLE
spike_train_generation - VisibleDeprecationWarning

### ISSUE THREAD

**Issue by gulpgiulia** [NeuralEnsemble/elephant#96]
Very very minor issue (it is only a warning, and I have checked on the web, it seems no serious and related to numpy... but maybe you want to check it, in order to have a "clean" output). I have followed the tutorial step-by-step (http://elephant.readthedocs.io/en/latest/tutorial.html)
[about this, excellent tutorial! very clear and well done. A suggestion: you can add a reference, for instance: P. Dayan and L.F. Abbot, "Theoretical Neuroscience" (2001, Par. 1.4)]. 
My NumPy is numpy==1.11.2
Details in the attached file. 
Thank you
[VisibleDeprecationWarning.txt](https://github.com/NeuralEnsemble/elephant/files/594357/VisibleDeprecationWarning.txt)

P.S. The warning appears only the first time you use "homogeneous_poisson_process" in the python session. Subsequent calls in the same session produce no warning messages.

**Comment by alperyeg** [comment]
@gulpgiulia. I am happy to hear that you liked the tutorials. If you want to see a longer tutorial, here is one me and colleagues of mine gave last year in Manchester while the code jam (https://github.com/INM-6/elephant-cs16/blob/master/notebooks/neo_elephant.v3.ipynb)

Regarding the problem, that's not a big issue. What happens is that one of the parameters of `numpy.random.exponential` or `numpy.random.gamma` expects an integer but gets a float. This problem only appears with newer versions of `numpy`. 
I can provide a fix.
